# Generated by Django 5.2.4 on 2025-09-27 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('records_processed', models.PositiveIntegerField(default=0)),
                ('records_created', models.PositiveIntegerField(default=0)),
                ('records_updated', models.PositiveIntegerField(default=0)),
                ('records_errors', models.PositiveIntegerField(default=0)),
                ('error_details', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('current_page', models.PositiveIntegerField(default=1, help_text='Aktualna strona podczas importu')),
            ],
            options={
                'verbose_name': 'Log synchronizacji API',
                'verbose_name_plural': 'Logi synchronizacji API',
                'db_table': 'apisynclog',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Marki',
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Saga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saga_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('saga_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('compensating', 'Compensating'), ('compensated', 'Compensated')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('total_steps', models.IntegerField(default=0)),
                ('completed_steps', models.IntegerField(default=0)),
                ('failed_step', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Saga Log',
                'verbose_name_plural': 'Saga Logs',
                'db_table': 'saga_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_uid', models.IntegerField(db_index=True, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('new_collection', models.BooleanField(default=False)),
                ('products_in_set', models.JSONField(blank=True, default=list)),
                ('other_colors', models.JSONField(blank=True, default=list)),
                ('prices', models.JSONField(blank=True, default=dict)),
                ('mapped_product_uid', models.IntegerField(blank=True, help_text='UID produktu w bazie MPD', null=True)),
                ('is_mapped', models.BooleanField(default=False, help_text='Czy produkt jest zmapowany do MPD')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_api_sync', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matterhorn1.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matterhorn1.category')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.CharField(blank=True, max_length=20, null=True)),
                ('size_table', models.TextField(blank=True, null=True)),
                ('size_table_txt', models.TextField(blank=True, null=True)),
                ('size_table_html', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='matterhorn1.product')),
            ],
            options={
                'verbose_name': 'Szczegóły produktu',
                'verbose_name_plural': 'Szczegóły produktów',
                'db_table': 'productdetails',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=1000)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='matterhorn1.product')),
            ],
            options={
                'verbose_name': 'Obraz produktu',
                'verbose_name_plural': 'Obrazy produktów',
                'db_table': 'productimage',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_uid', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('max_processing_time', models.PositiveIntegerField(default=0)),
                ('ean', models.CharField(blank=True, max_length=20)),
                ('mapped_variant_uid', models.IntegerField(blank=True, help_text='UID wariantu w bazie MPD', null=True)),
                ('is_mapped', models.BooleanField(blank=True, help_text='Czy wariant jest zmapowany do MPD', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='matterhorn1.product')),
            ],
            options={
                'verbose_name': 'Wariant produktu',
                'verbose_name_plural': 'Warianty produktów',
                'db_table': 'productvariant',
            },
        ),
        migrations.CreateModel(
            name='SagaStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=100)),
                ('step_order', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('compensating', 'Compensating'), ('compensated', 'Compensated')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('compensated_at', models.DateTimeField(blank=True, null=True)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('compensation_attempted', models.BooleanField(default=False)),
                ('compensation_successful', models.BooleanField(default=False)),
                ('saga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='matterhorn1.saga')),
            ],
            options={
                'verbose_name': 'Saga Step',
                'verbose_name_plural': 'Saga Steps',
                'db_table': 'saga_steps',
                'ordering': ['saga', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('variant_uid', models.CharField(db_index=True, max_length=50)),
                ('product_uid', models.IntegerField(db_index=True, help_text='ID produktu z API Matterhorn')),
                ('product_name', models.CharField(blank=True, max_length=500, null=True)),
                ('variant_name', models.CharField(blank=True, max_length=50, null=True)),
                ('old_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('new_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('stock_change', models.IntegerField(blank=True, null=True)),
                ('change_type', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historia stanów magazynowych',
                'verbose_name_plural': 'Historia stanów magazynowych',
                'db_table': 'stock_history',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['variant_uid'], name='mh1_sh_variant_idx'), models.Index(fields=['product_uid'], name='mh1_sh_product_idx'), models.Index(fields=['timestamp'], name='mh1_sh_timestamp_idx'), models.Index(fields=['change_type'], name='mh1_sh_change_idx'), models.Index(fields=['product_uid', 'timestamp'], name='mh1_sh_prod_time_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_uid'], name='product_product_bdf661_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['active'], name='product_active_9516cd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='product_brand_i_080bb1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='product_categor_26b384_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together={('product', 'image_url')},
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['variant_uid'], name='productvari_variant_a798bd_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product'], name='productvari_product_40111c_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['ean'], name='productvari_ean_f9d897_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['is_mapped'], name='productvari_is_mapp_bb6444_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['mapped_variant_uid'], name='productvari_mapped__6a3c85_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sagastep',
            unique_together={('saga', 'step_order')},
        ),
    ]
