# Generated by Django 5.2.4 on 2025-09-16 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matterhorn1', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='matterhorn1_product_2a32ff_idx',
            old_name='matterhorn1_product_32a0ac_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='matterhorn1_active_189585_idx',
            old_name='matterhorn1_active_927d89_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='matterhorn1_brand_i_122f01_idx',
            old_name='matterhorn1_brand_i_4fb875_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='matterhorn1_categor_156370_idx',
            old_name='matterhorn1_categor_f79bdd_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='matterhorn1_variant_8e9cff_idx',
            old_name='matterhorn1_variant_e039dd_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='matterhorn1_product_41b642_idx',
            old_name='matterhorn1_product_bfc740_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='matterhorn1_ean_07d813_idx',
            old_name='matterhorn1_ean_0799c8_idx',
        ),
        migrations.AlterModelTable(
            name='apisynclog',
            table=None,
        ),
        migrations.AlterModelTable(
            name='brand',
            table=None,
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
        migrations.AlterModelTable(
            name='productdetails',
            table=None,
        ),
        migrations.AlterModelTable(
            name='productimage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='productvariant',
            table=None,
        ),
    ]
