# Generated by Django 5.2.4 on 2025-09-17 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matterhorn1', '0002_rename_matterhorn1_product_32a0ac_idx_matterhorn1_product_2a32ff_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='product_product_a470af_idx',
            old_name='matterhorn1_product_2a32ff_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='product_active_9516cd_idx',
            old_name='matterhorn1_active_189585_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='product_brand_i_080bb1_idx',
            old_name='matterhorn1_brand_i_122f01_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='product_categor_26b384_idx',
            old_name='matterhorn1_categor_156370_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='productvari_variant_a798bd_idx',
            old_name='matterhorn1_variant_8e9cff_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='productvari_product_40111c_idx',
            old_name='matterhorn1_product_41b642_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='productvari_ean_f9d897_idx',
            old_name='matterhorn1_ean_07d813_idx',
        ),
        migrations.AlterModelTable(
            name='apisynclog',
            table='apisynclog',
        ),
        migrations.AlterModelTable(
            name='brand',
            table='brand',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='productdetails',
            table='productdetails',
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='productimage',
        ),
        migrations.AlterModelTable(
            name='productvariant',
            table='productvariant',
        ),
    ]
