# Generated by Django 5.2.4 on 2025-09-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matterhorn1', '0003_rename_matterhorn1_product_2a32ff_idx_product_product_a470af_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
