# Generated by Django 5.2.4 on 2025-09-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matterhorn1', '0004_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='size_table',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='size_table_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='size_table_txt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='weight',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
