# Generated by Django 5.2.4 on 2025-09-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matterhorn1', '0005_alter_productdetails_size_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisynclog',
            name='current_page',
            field=models.PositiveIntegerField(default=1, help_text='Aktualna strona podczas importu'),
        ),
        migrations.AddField(
            model_name='apisynclog',
            name='last_imported_id',
            field=models.PositiveIntegerField(default=0, help_text='Ostatni zaimportowany ID produktu'),
        ),
    ]
