# Generated by Django 5.2.4 on 2025-09-18 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matterhorn1', '0006_apisynclog_current_page_apisynclog_last_imported_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apisynclog',
            name='last_imported_id',
        ),
    ]
