# Generated by Django 5.2.4 on 2025-09-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matterhorn1', '0007_remove_apisynclog_last_imported_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mapped_product_id',
            field=models.IntegerField(blank=True, help_text='ID produktu w bazie MPD', null=True),
        ),
    ]
