# Generated by Django 5.2.4 on 2025-09-19 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matterhorn1', '0008_product_mapped_product_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together={('product', 'image_url')},
        ),
    ]
