# Generated by Django 5.2.4 on 2025-09-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matterhorn1', '0009_alter_productimage_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_mapped',
            field=models.BooleanField(default=False, help_text='Czy produkt jest zmapowany do MPD'),
        ),
    ]
