# Generated by Django 5.2.4 on 2025-09-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matterhorn1', '0010_product_is_mapped'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_mapped',
            field=models.BooleanField(default=False, help_text='Czy wariant jest zmapowany do MPD'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='mapped_variant_id',
            field=models.IntegerField(blank=True, help_text='ID wariantu w bazie MPD', null=True),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['is_mapped'], name='productvari_is_mapp_bb6444_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['mapped_variant_id'], name='productvari_mapped__f67145_idx'),
        ),
    ]
