# Generated by Django 5.2.4 on 2025-09-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matterhorn1', '0011_productvariant_is_mapped_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='is_mapped',
            field=models.BooleanField(blank=True, help_text='Czy wariant jest zmapowany do MPD', null=True),
        ),
    ]
