# Generated by Django 5.2.4 on 2025-09-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matterhorn1', '0013_create_saga_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('variant_uid', models.CharField(db_index=True, max_length=50)),
                ('product_uid', models.IntegerField(db_index=True, help_text='ID produktu z API Matterhorn')),
                ('product_name', models.CharField(blank=True, max_length=500, null=True)),
                ('variant_name', models.CharField(blank=True, max_length=50, null=True)),
                ('old_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('new_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('stock_change', models.IntegerField(blank=True, null=True)),
                ('change_type', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historia stanów magazynowych',
                'verbose_name_plural': 'Historia stanów magazynowych',
                'db_table': 'stock_history',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveIndex(
            model_name='productvariant',
            name='productvari_mapped__f67145_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mapped_product_id',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='mapped_variant_id',
        ),
        migrations.AddField(
            model_name='product',
            name='mapped_product_uid',
            field=models.IntegerField(blank=True, help_text='UID produktu w bazie MPD', null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='mapped_variant_uid',
            field=models.IntegerField(blank=True, help_text='UID wariantu w bazie MPD', null=True),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['mapped_variant_uid'], name='productvari_mapped__6a3c85_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhistory',
            index=models.Index(fields=['variant_uid'], name='mh1_sh_variant_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhistory',
            index=models.Index(fields=['product_uid'], name='mh1_sh_product_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhistory',
            index=models.Index(fields=['timestamp'], name='mh1_sh_timestamp_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhistory',
            index=models.Index(fields=['change_type'], name='mh1_sh_change_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhistory',
            index=models.Index(fields=['product_uid', 'timestamp'], name='mh1_sh_prod_time_idx'),
        ),
    ]
