# Generated by Django 5.2.4 on 2025-09-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matterhorn1', '0014_stockhistory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_id',
            new_name='product_uid',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_uid',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
