# Generated by Django 5.2.4 on 2025-09-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matterhorn1', '0015_auto_20250926_1003'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='product_product_a470af_idx',
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_uid'], name='product_product_bdf661_idx'),
        ),
    ]
