services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate --database=default && gunicorn nc.wsgi:application --bind 0.0.0.0:8000 --workers 4 --timeout 300 --keep-alive 5"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - ./static:/app/static
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    restart: always
    depends_on:
      - redis

  celery-import:
    build: .
    command: celery -A nc.celery worker -Q import_queue --loglevel=info --concurrency=1
    volumes:
      - .:/app
      - celery_data:/var/lib/celery
    env_file:
      - .env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=nc.settings.dev
      - CELERY_STATE_DB=/var/lib/celery/worker_state_import
    depends_on:
      - redis
      - web

  celery-default:
    build: .
    command: celery -A nc.celery worker -Q default --loglevel=info --concurrency=4
    volumes:
      - .:/app
      - celery_data:/var/lib/celery
    env_file:
      - .env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=nc.settings.dev
      - CELERY_STATE_DB=/var/lib/celery/worker_state_default
    depends_on:
      - redis
      - web

  celery-beat:
    build: .
    command: celery -A nc.celery beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=nc.settings.dev
    depends_on:
      - redis
      - web

  flower:
    build: .
    command: celery -A nc.celery flower --port=5555
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    env_file:
      - .env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=nc.settings.dev
    depends_on:
      - redis
      - celery-import
      - celery-default

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

volumes:
  static_volume:
  celery_data: 