services:
  web:
    build: .
    command: [ "/bin/bash", "-c", "python manage.py makemigrations && python manage.py migrate --database=default && python manage.py runserver 0.0.0.0:8000" ]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    env_file:
      - .env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=nc.settings.dev
      - TZ=Europe/Warsaw
      - PYTHONUNBUFFERED=1
      - DJANGO_DEBUG=1
      - REDIS_PASSWORD=dev_password
    restart: always
    networks:
      - app_network
    depends_on:
      - redis

  celery-import:
    build: .
    command: [ "/bin/bash", "-c", "sleep 10 && celery -A nc.celery worker -Q import_queue --loglevel=info --concurrency=1" ]
    volumes:
      - .:/app
      - celery_data:/var/lib/celery
    env_file:
      - .env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=nc.settings.dev
      - CELERY_STATE_DB=/var/lib/celery/worker_state_import
      - TZ=Europe/Warsaw
      - C_FORCE_ROOT=true
      - REDIS_PASSWORD=dev_password
      - CELERY_BROKER_URL=redis://:dev_password@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:dev_password@redis:6379/0
      - CELERY_WORKER_ENABLE_REMOTE_CONTROL=true
      - CELERY_WORKER_SEND_TASK_EVENTS=true
      - CELERY_TASK_SEND_SENT_EVENT=true
    depends_on:
      - web
      - redis
    restart: always
    networks:
      - app_network

  celery-default:
    build: .
    command: [ "/bin/bash", "-c", "sleep 10 && celery -A nc.celery worker -Q default --loglevel=info --concurrency=2" ]
    volumes:
      - .:/app
      - celery_data:/var/lib/celery
    env_file:
      - .env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=nc.settings.dev
      - CELERY_STATE_DB=/var/lib/celery/worker_state_default
      - TZ=Europe/Warsaw
      - C_FORCE_ROOT=true
      - REDIS_PASSWORD=dev_password
      - CELERY_BROKER_URL=redis://:dev_password@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:dev_password@redis:6379/0
      - CELERY_WORKER_ENABLE_REMOTE_CONTROL=true
      - CELERY_WORKER_SEND_TASK_EVENTS=true
      - CELERY_TASK_SEND_SENT_EVENT=true
    depends_on:
      - web
      - redis
    restart: always
    networks:
      - app_network

  celery-beat:
    build: .
    command: [ "/bin/bash", "-c", "celery -A nc.celery beat --loglevel=info" ]
    volumes:
      - .:/app
    env_file:
      - .env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=nc.settings.dev
      - TZ=Europe/Warsaw
      - REDIS_PASSWORD=dev_password
      - CELERY_BROKER_URL=redis://:dev_password@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:dev_password@redis:6379/0
    depends_on:
      - web
      - redis
    restart: always
    networks:
      - app_network

  flower:
    build: .
    command: [ "/bin/bash", "-c", "sleep 120 && celery -A nc.celery --broker=redis://:dev_password@redis:6379/0 flower --port=5555 --persistent=True --db=/var/lib/flower/flower.db --inspect_timeout=30" ]
    ports:
      - "5555:5555"
    volumes:
      - .:/app
      - flower_data:/var/lib/flower
    env_file:
      - .env.dev
    environment:
      - DJANGO_SETTINGS_MODULE=nc.settings.dev
      - TZ=Europe/Warsaw
      - C_FORCE_ROOT=true
      - REDIS_PASSWORD=dev_password
      - CELERY_BROKER_URL=redis://:dev_password@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:dev_password@redis:6379/0
      - CELERY_WORKER_ENABLE_REMOTE_CONTROL=true
      - CELERY_WORKER_SEND_TASK_EVENTS=true
      - CELERY_TASK_SEND_SENT_EVENT=true
      - CELERY_TASK_EVENTS=true
      - CELERY_WORKER_SEND_TASK_EVENTS=true
      - CELERY_TASK_SEND_SENT_EVENT=true
      - CELERY_TASK_TRACK_STARTED=true
      - CELERY_TASK_IGNORE_RESULT=false
      - CELERY_TASK_STORE_EAGER_RESULT=true
    depends_on:
      - redis
      - celery-import
      - celery-default
    networks:
      - app_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - TZ=Europe/Warsaw
      - REDIS_PASSWORD=dev_password
    restart: always
    networks:
      - app_network
    command: redis-server --requirepass dev_password --maxmemory 100mb --maxmemory-policy allkeys-lru --protected-mode no

volumes:
  static_volume:
  celery_data:
  flower_data:
    driver: local

networks:
  app_network:
    driver: bridge
