server {
    listen 80;
    server_name _;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log debug;

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /app/staticfiles/;
        access_log /var/log/nginx/static_access.log;
        error_log /var/log/nginx/static_error.log;
        expires max;
        add_header Cache-Control "public, immutable";
        # Włącz autoindex dla debugowania (opcjonalnie)
        # autoindex on;
        # Dodaj typy MIME dla plików CSS i JS
        types {
            text/css css;
            application/javascript js;
            image/png png;
            image/jpeg jpg jpeg;
            image/gif gif;
            image/svg+xml svg;
        }
        default_type application/octet-stream;
    }
}
