# Redis configuration file

# Basic configuration
bind 0.0.0.0
port 6379
timeout 0
tcp-keepalive 300

# Security
requirepass ${REDIS_PASSWORD:-twoje_silne_haslo}

# Memory management
maxmemory 100mb
maxmemory-policy allkeys-lru

# Persistence
save 900 1
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
dir ./

# Logging
loglevel notice
logfile ""

# Other settings
daemonize no
supervised no
pidfile /var/run/redis_6379.pid 