# Generated by Django 5.2.4 on 2025-12-03 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Rozpoczęto')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Zakończono')),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('running', 'W trakcie'), ('completed', 'Zakończone'), ('failed', 'Błąd')], default='pending', max_length=20, verbose_name='Status')),
                ('products_processed', models.IntegerField(default=0, verbose_name='Przetworzono produktów')),
                ('products_success', models.IntegerField(default=0, verbose_name='Sukces')),
                ('products_failed', models.IntegerField(default=0, verbose_name='Błędy')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Komunikat błędu')),
                ('brand_id', models.IntegerField(blank=True, null=True, verbose_name='ID marki')),
                ('category_id', models.IntegerField(blank=True, null=True, verbose_name='ID kategorii')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='Filtry')),
            ],
            options={
                'verbose_name': 'Uruchomienie automatyzacji',
                'verbose_name_plural': 'Uruchomienia automatyzacji',
                'db_table': 'automation_run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductProcessingLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField(verbose_name='ID produktu')),
                ('product_name', models.CharField(blank=True, max_length=500, verbose_name='Nazwa produktu')),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('processing', 'Przetwarzanie'), ('success', 'Sukces'), ('failed', 'Błąd')], default='pending', max_length=20, verbose_name='Status')),
                ('mpd_product_id', models.IntegerField(blank=True, null=True, verbose_name='ID produktu w MPD')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Komunikat błędu')),
                ('processed_at', models.DateTimeField(auto_now_add=True, verbose_name='Przetworzono')),
                ('processing_data', models.JSONField(blank=True, default=dict, verbose_name='Dane przetwarzania')),
                ('automation_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_logs', to='web_agent.automationrun', verbose_name='Uruchomienie automatyzacji')),
            ],
            options={
                'verbose_name': 'Log przetwarzania produktu',
                'verbose_name_plural': 'Logi przetwarzania produktów',
                'db_table': 'product_processing_log',
                'ordering': ['-processed_at'],
                'indexes': [models.Index(fields=['automation_run', 'status'], name='product_pro_automat_d89ce7_idx'), models.Index(fields=['product_id'], name='product_pro_product_c3f881_idx')],
            },
        ),
    ]
