# Generated by Django 5.2.4 on 2025-12-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_agent', '0002_brandconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerColor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('brand_id', models.IntegerField(db_index=True, verbose_name='ID marki')),
                ('brand_name', models.CharField(max_length=200, verbose_name='Nazwa marki')),
                ('color_name', models.CharField(max_length=200, verbose_name='Nazwa koloru producenta')),
                ('normalized_color', models.CharField(blank=True, help_text='Znormalizowana wersja nazwy koloru do porównań', max_length=200, null=True, verbose_name='Znormalizowana nazwa koloru')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Liczba użyć')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
            ],
            options={
                'verbose_name': 'Kolor producenta',
                'verbose_name_plural': 'Kolory producenta',
                'db_table': 'producer_color',
                'ordering': ['brand_name', 'color_name'],
                'indexes': [models.Index(fields=['brand_id', 'color_name'], name='producer_co_brand_i_74d6a1_idx'), models.Index(fields=['brand_name'], name='producer_co_brand_n_d62f42_idx')],
                'unique_together': {('brand_id', 'color_name')},
            },
        ),
    ]
