# Generated by Django 5.2.4 on 2025-12-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_agent', '0004_automationrun_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandconfig',
            name='category_config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON z konfiguracją dla każdej kategorii. Przykład: {"Kostiumy dwuczęściowe": {"path_value": "5", "base_type": "Kostium kąpielowy", "has_top": true}, "Jednoczęściowe": {"path_value": "7", "base_type": "Kostium kąpielowy", "has_top": true}, "Figi kąpielowe": {"path_value": "6", "base_type": "Figi kąpielowe", "has_top": false}}', verbose_name='Konfiguracja kategorii'),
        ),
    ]
