# Generated by Django 5.2.4 on 2025-12-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_agent', '0005_brandconfig_category_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandconfig',
            name='category_config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON z konfiguracją dla każdej kategorii. Przykład: {"Kostiumy dwuczęściowe": {"path_value": "5", "base_type": "Kostium kąpielowy", "has_top": true}, "Jednoczęściowe": {"path_value": "7", "base_type": "Jednoczęściowy kostium kąpielowy", "has_top": true}, "Figi kąpielowe": {"path_value": "6", "base_type": "Figi kąpielowe", "has_top": false}}', verbose_name='Konfiguracja kategorii'),
        ),
        migrations.CreateModel(
            name='AIPrompt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Unikalna nazwa promptu (np. "product_description_system", "product_name_user_figi")', max_length=200, unique=True, verbose_name='Nazwa promptu')),
                ('prompt_type', models.CharField(choices=[('system', 'System'), ('user', 'User')], help_text='System prompt (instrukcje) lub User prompt (zadanie)', max_length=20, verbose_name='Typ promptu')),
                ('category', models.CharField(choices=[('description', 'Opis produktu'), ('name', 'Nazwa produktu'), ('attributes', 'Ekstrakcja atrybutów'), ('legacy', 'Legacy enhancement')], help_text='Kategoria promptu (description, name, attributes, legacy)', max_length=50, verbose_name='Kategoria')),
                ('content', models.TextField(help_text='Treść promptu. Możesz użyć zmiennych w formacie {variable_name} (np. {base_type}, {has_top}, {description_sections})', verbose_name='Treść promptu')),
                ('variables', models.JSONField(blank=True, default=list, help_text='Lista zmiennych używanych w prompcie (np. ["base_type", "has_top", "description_sections"])', verbose_name='Zmienne')),
                ('is_active', models.BooleanField(default=True, help_text='Czy prompt jest aktywny (używany w automatyzacji)', verbose_name='Aktywny')),
                ('description', models.TextField(blank=True, help_text='Opis promptu i jego przeznaczenia', verbose_name='Opis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
            ],
            options={
                'verbose_name': 'Prompt AI',
                'verbose_name_plural': 'Prompty AI',
                'db_table': 'ai_prompt',
                'ordering': ['category', 'prompt_type', 'name'],
                'indexes': [models.Index(fields=['category', 'prompt_type', 'is_active'], name='ai_prompt_categor_f5df0c_idx'), models.Index(fields=['name'], name='ai_prompt_name_c9491d_idx')],
            },
        ),
    ]
