# Generated by Django 5.2 on 2025-04-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('name_without_number', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.CharField(blank=True, max_length=40, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('category_path', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_id', models.IntegerField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_total', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('new_collection', models.CharField(blank=True, max_length=5, null=True)),
                ('size_table', models.TextField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('size_table_txt', models.TextField(blank=True, null=True)),
                ('size_table_html', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField()),
                ('mapped_product_id', models.IntegerField(blank=True, null=True)),
                ('is_mapped', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
    ]
