# Generated by Django 5.1.7 on 2025-04-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_path', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OtherColors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Other Colors',
                'db_table': 'other_colors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductInSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Product In Set',
                'db_table': 'product_in_set',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('name_without_number', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.CharField(blank=True, max_length=40, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('category_path', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_id', models.IntegerField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_total', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('new_collection', models.CharField(blank=True, max_length=5, null=True)),
                ('size_table', models.TextField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('size_table_txt', models.TextField(blank=True, null=True)),
                ('size_table_html', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField()),
                ('mapped_product_id', models.IntegerField(blank=True, null=True)),
                ('is_mapped', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('data_items', models.TextField(blank=True, null=True)),
                ('data_inventory', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'update_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('variant_uid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('max_processing_time', models.IntegerField(blank=True, null=True)),
                ('ean', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField()),
                ('mapped_variant_id', models.IntegerField(blank=True, null=True)),
                ('is_mapped', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Variants',
                'db_table': 'variants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Mapper',
                'verbose_name_plural': 'Mapper',
                'managed': False,
                'proxy': True,
            },
            bases=('matterhorn.products',),
        ),
    ]
