# Generated by Django 5.2 on 2025-05-03 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matterhorn', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinset',
            options={'managed': False, 'verbose_name_plural': 'Product in Series'},
        ),
    ]
