# Generated by Django 5.2.4 on 2025-09-27 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matterhorn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('data_items', models.TextField(blank=True, null=True)),
                ('data_inventory', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'update_log',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('name_without_number', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.CharField(blank=True, max_length=40, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('category_name', models.CharField(blank=True, max_length=255, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('category_path', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_id', models.IntegerField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('stock_total', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('new_collection', models.CharField(blank=True, max_length=5, null=True)),
                ('size_table', models.TextField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('size_table_txt', models.TextField(blank=True, null=True)),
                ('size_table_html', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField()),
                ('mapped_product_id', models.IntegerField(blank=True, null=True)),
                ('is_mapped', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'managed': True,
                'indexes': [models.Index(fields=['active'], name='products_active_20e15c_idx'), models.Index(fields=['category_name'], name='products_categor_f86cfe_idx'), models.Index(fields=['brand'], name='products_brand_b2547a_idx'), models.Index(fields=['is_mapped'], name='products_is_mapp_92ca4b_idx'), models.Index(fields=['mapped_product_id'], name='products_mapped__9a8710_idx'), models.Index(fields=['last_updated'], name='products_last_up_b1d6ad_idx'), models.Index(fields=['timestamp'], name='products_timesta_4b3b5c_idx'), models.Index(fields=['category_id'], name='products_categor_4083ff_idx'), models.Index(fields=['brand_id'], name='products_brand_i_0d1950_idx'), models.Index(fields=['active', 'category_name'], name='products_active_1c36c7_idx'), models.Index(fields=['is_mapped', 'mapped_product_id'], name='products_is_mapp_8e7019_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Mapper',
                'verbose_name_plural': 'Mapper',
                'managed': True,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('matterhorn.products',),
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('variant_uid', models.PositiveIntegerField()),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('variant_name', models.CharField(blank=True, max_length=50, null=True)),
                ('old_stock', models.IntegerField(blank=True, null=True)),
                ('new_stock', models.IntegerField(blank=True, null=True)),
                ('stock_change', models.IntegerField(blank=True, null=True)),
                ('change_type', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Stock History',
                'db_table': 'stock_history',
                'managed': True,
                'indexes': [models.Index(fields=['variant_uid'], name='stock_histo_variant_7e9b92_idx'), models.Index(fields=['product_id'], name='stock_histo_product_b99fef_idx'), models.Index(fields=['timestamp'], name='stock_histo_timesta_bd1231_idx'), models.Index(fields=['change_type'], name='stock_histo_change__77d37d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductInSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_in_set', to='matterhorn.products')),
                ('set_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productinset_set_product_id', to='matterhorn.products')),
            ],
            options={
                'verbose_name_plural': 'Product in Series',
                'db_table': 'product_in_set',
                'managed': True,
                'indexes': [models.Index(fields=['product'], name='product_in__product_cd57de_idx'), models.Index(fields=['set_product'], name='product_in__set_pro_f9e68d_idx')],
                'unique_together': {('product', 'set_product')},
            },
        ),
        migrations.CreateModel(
            name='OtherColors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('color_product', models.ForeignKey(blank=True, db_column='color_product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='othercolors_color_product_id', to='matterhorn.products')),
                ('product', models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_colors', to='matterhorn.products')),
            ],
            options={
                'verbose_name_plural': 'Other Colors',
                'db_table': 'other_colors',
                'managed': True,
                'indexes': [models.Index(fields=['product'], name='other_color_product_ab84c6_idx'), models.Index(fields=['color_product'], name='other_color_color_p_13429f_idx')],
                'unique_together': {('product', 'color_product')},
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_path', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='matterhorn.products')),
            ],
            options={
                'db_table': 'images',
                'managed': True,
                'indexes': [models.Index(fields=['product'], name='images_product_53db6b_idx'), models.Index(fields=['timestamp'], name='images_timesta_0634b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('variant_uid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('max_processing_time', models.IntegerField(blank=True, null=True)),
                ('ean', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField()),
                ('mapped_variant_id', models.IntegerField(blank=True, null=True)),
                ('is_mapped', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='matterhorn.products')),
            ],
            options={
                'verbose_name_plural': 'Variants',
                'db_table': 'variants',
                'managed': True,
                'indexes': [models.Index(fields=['product'], name='variants_product_76d428_idx'), models.Index(fields=['is_mapped'], name='variants_is_mapp_55d297_idx'), models.Index(fields=['mapped_variant_id'], name='variants_mapped__82fe16_idx'), models.Index(fields=['last_updated'], name='variants_last_up_3edfe0_idx'), models.Index(fields=['timestamp'], name='variants_timesta_273ed0_idx'), models.Index(fields=['ean'], name='variants_ean_f8fa54_idx'), models.Index(fields=['product', 'is_mapped'], name='variants_product_eb88bd_idx'), models.Index(fields=['last_updated', 'product'], name='variants_last_up_e7cbec_idx')],
            },
        ),
    ]
