# Generated by Django 5.2 on 2025-06-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matterhorn', '0002_alter_productinset_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('variant_uid', models.PositiveIntegerField()),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('variant_name', models.CharField(blank=True, max_length=50, null=True)),
                ('old_stock', models.IntegerField(blank=True, null=True)),
                ('new_stock', models.IntegerField(blank=True, null=True)),
                ('stock_change', models.IntegerField(blank=True, null=True)),
                ('change_type', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Stock History',
                'db_table': 'stock_history',
                'managed': False,
            },
        ),
    ]
