# Generated by Django 5.2.4 on 2025-09-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matterhorn', '0003_stockhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductsProxy',
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='othercolors',
            options={'managed': True, 'verbose_name_plural': 'Other Colors'},
        ),
        migrations.AlterModelOptions(
            name='productinset',
            options={'managed': True, 'verbose_name_plural': 'Product in Series'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'managed': True, 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='stockhistory',
            options={'managed': True, 'verbose_name_plural': 'Stock History'},
        ),
        migrations.AlterModelOptions(
            name='updatelog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='variants',
            options={'managed': True, 'verbose_name_plural': 'Variants'},
        ),
        migrations.CreateModel(
            name='ProductsProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Mapper',
                'verbose_name_plural': 'Mapper',
                'managed': True,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('matterhorn.products',),
        ),
    ]
