# Generated by Django 5.2.4 on 2025-09-01 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matterhorn', '0004_delete_productsproxy_alter_images_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='matterhorn.products'),
        ),
        migrations.AddField(
            model_name='othercolors',
            name='color_product',
            field=models.ForeignKey(blank=True, db_column='color_product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='othercolors_color_product_id', to='matterhorn.products'),
        ),
        migrations.AddField(
            model_name='othercolors',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_colors', to='matterhorn.products'),
        ),
        migrations.AddField(
            model_name='productinset',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_in_set', to='matterhorn.products'),
        ),
        migrations.AddField(
            model_name='productinset',
            name='set_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productinset_set_product_id', to='matterhorn.products'),
        ),
        migrations.AddField(
            model_name='variants',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='matterhorn.products'),
        ),
        migrations.AlterUniqueTogether(
            name='othercolors',
            unique_together={('product', 'color_product')},
        ),
        migrations.AlterUniqueTogether(
            name='productinset',
            unique_together={('product', 'set_product')},
        ),
        migrations.AddIndex(
            model_name='othercolors',
            index=models.Index(fields=['product'], name='other_color_product_ab84c6_idx'),
        ),
        migrations.AddIndex(
            model_name='othercolors',
            index=models.Index(fields=['color_product'], name='other_color_color_p_13429f_idx'),
        ),
        migrations.AddIndex(
            model_name='productinset',
            index=models.Index(fields=['product'], name='product_in__product_cd57de_idx'),
        ),
        migrations.AddIndex(
            model_name='productinset',
            index=models.Index(fields=['set_product'], name='product_in__set_pro_f9e68d_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhistory',
            index=models.Index(fields=['variant_uid'], name='stock_histo_variant_7e9b92_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhistory',
            index=models.Index(fields=['product_id'], name='stock_histo_product_b99fef_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhistory',
            index=models.Index(fields=['timestamp'], name='stock_histo_timesta_bd1231_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhistory',
            index=models.Index(fields=['change_type'], name='stock_histo_change__77d37d_idx'),
        ),
        migrations.AddIndex(
            model_name='variants',
            index=models.Index(fields=['product'], name='variants_product_76d428_idx'),
        ),
    ]
