# Generated by Django 5.2.4 on 2025-09-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matterhorn', '0005_images_product_othercolors_color_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='active',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='brand_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='category_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='category_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_mapped',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='last_updated',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='mapped_product_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='new_collection',
            field=models.CharField(blank=True, db_index=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='updatelog',
            name='last_update',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='images',
            index=models.Index(fields=['product', 'timestamp'], name='images_product_c2d1a2_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['active', 'category_name'], name='products_active_1c36c7_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['brand', 'category_name'], name='products_brand_ddc1a5_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['is_mapped', 'mapped_product_id'], name='products_is_mapp_8e7019_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['timestamp', 'last_updated'], name='products_timesta_9e7c77_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['price', 'stock_total'], name='products_price_cc620e_idx'),
        ),
        migrations.AddIndex(
            model_name='updatelog',
            index=models.Index(fields=['last_update'], name='update_log_last_up_c70e0e_idx'),
        ),
    ]
