# Generated by Django 5.2.4 on 2025-09-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matterhorn', '0006_alter_images_timestamp_alter_products_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variants',
            name='ean',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='variants',
            name='is_mapped',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='variants',
            name='last_updated',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='variants',
            name='mapped_variant_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='variants',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='variants',
            name='stock',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='variants',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='variants',
            index=models.Index(fields=['is_mapped', 'mapped_variant_id'], name='variants_is_mapp_940228_idx'),
        ),
        migrations.AddIndex(
            model_name='variants',
            index=models.Index(fields=['stock', 'timestamp'], name='variants_stock_d93d49_idx'),
        ),
        migrations.AddIndex(
            model_name='variants',
            index=models.Index(fields=['ean', 'name'], name='variants_ean_9cda1f_idx'),
        ),
    ]
