# Generated by Django 5.2.4 on 2025-09-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matterhorn', '0007_alter_variants_ean_alter_variants_is_mapped_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='images',
            name='images_product_c2d1a2_idx',
        ),
        migrations.RemoveIndex(
            model_name='products',
            name='products_brand_ddc1a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='products',
            name='products_timesta_9e7c77_idx',
        ),
        migrations.RemoveIndex(
            model_name='products',
            name='products_price_cc620e_idx',
        ),
        migrations.RemoveIndex(
            model_name='updatelog',
            name='update_log_last_up_c70e0e_idx',
        ),
        migrations.RemoveIndex(
            model_name='variants',
            name='variants_is_mapp_940228_idx',
        ),
        migrations.RemoveIndex(
            model_name='variants',
            name='variants_stock_d93d49_idx',
        ),
        migrations.RemoveIndex(
            model_name='variants',
            name='variants_ean_9cda1f_idx',
        ),
        migrations.AlterField(
            model_name='images',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='active',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='brand_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='category_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_mapped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='mapped_product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='new_collection',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='updatelog',
            name='last_update',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='variants',
            name='ean',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='variants',
            name='is_mapped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='variants',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variants',
            name='mapped_variant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variants',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='variants',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variants',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name='images',
            index=models.Index(fields=['product'], name='images_product_53db6b_idx'),
        ),
        migrations.AddIndex(
            model_name='images',
            index=models.Index(fields=['timestamp'], name='images_timesta_0634b7_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['active'], name='products_active_20e15c_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['category_name'], name='products_categor_f86cfe_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['brand'], name='products_brand_b2547a_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['is_mapped'], name='products_is_mapp_92ca4b_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['mapped_product_id'], name='products_mapped__9a8710_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['last_updated'], name='products_last_up_b1d6ad_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['timestamp'], name='products_timesta_4b3b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['category_id'], name='products_categor_4083ff_idx'),
        ),
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['brand_id'], name='products_brand_i_0d1950_idx'),
        ),
        migrations.AddIndex(
            model_name='variants',
            index=models.Index(fields=['is_mapped'], name='variants_is_mapp_55d297_idx'),
        ),
        migrations.AddIndex(
            model_name='variants',
            index=models.Index(fields=['mapped_variant_id'], name='variants_mapped__82fe16_idx'),
        ),
        migrations.AddIndex(
            model_name='variants',
            index=models.Index(fields=['last_updated'], name='variants_last_up_3edfe0_idx'),
        ),
        migrations.AddIndex(
            model_name='variants',
            index=models.Index(fields=['timestamp'], name='variants_timesta_273ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='variants',
            index=models.Index(fields=['ean'], name='variants_ean_f8fa54_idx'),
        ),
        migrations.AddIndex(
            model_name='variants',
            index=models.Index(fields=['product', 'is_mapped'], name='variants_product_eb88bd_idx'),
        ),
        migrations.AddIndex(
            model_name='variants',
            index=models.Index(fields=['last_updated', 'product'], name='variants_last_up_e7cbec_idx'),
        ),
    ]
