#!/bin/bash

# Nginx Security Setup Script
# Konfiguruje dodatkowe zabezpieczenia nginx

echo "🔒 Setting up Nginx Security..."

# Utwórz katalog na logi bezpieczeństwa
mkdir -p logs/nginx_security

# Utwórz katalog na blokowane IP
mkdir -p /etc/nginx/conf.d/security

# Skopiuj konfigurację nginx
echo "📋 Copying nginx configuration..."
cp nginx.conf /etc/nginx/conf.d/default.conf

# Utwórz dodatkową konfigurację bezpieczeństwa
cat > /etc/nginx/conf.d/security/rate_limits.conf << 'EOF'
# Rate limiting configuration
limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;
limit_req_zone $binary_remote_addr zone=static:10m rate=30r/s;
limit_req_zone $binary_remote_addr zone=login:10m rate=5r/m;

# Connection limiting
limit_conn_zone $binary_remote_addr zone=conn_limit_per_ip:10m;
limit_conn_zone $server_name zone=conn_limit_per_server:10m;
EOF

# Utwórz konfigurację blokowania IP
cat > /etc/nginx/conf.d/security/blocked_ips.conf << 'EOF'
# Blocked IPs (generated by security monitor)
# Add blocked IPs here
# deny 192.168.1.100;
# deny 10.0.0.0/8;
EOF

# Utwórz skrypt do automatycznego blokowania
cat > /usr/local/bin/nginx_block_ip.sh << 'EOF'
#!/bin/bash
# Script to block IP in nginx configuration

IP=$1
REASON=$2

if [ -z "$IP" ]; then
    echo "Usage: $0 <IP> <reason>"
    exit 1
fi

# Add IP to blocked list
echo "deny $IP; # Blocked: $REASON - $(date)" >> /etc/nginx/conf.d/security/blocked_ips.conf

# Test nginx configuration
if nginx -t; then
    # Reload nginx
    nginx -s reload
    echo "IP $IP blocked successfully"
else
    echo "Error: Invalid nginx configuration"
    # Remove the line we just added
    sed -i "/deny $IP;/d" /etc/nginx/conf.d/security/blocked_ips.conf
    exit 1
fi
EOF

chmod +x /usr/local/bin/nginx_block_ip.sh

# Utwórz skrypt do monitorowania
cat > /usr/local/bin/nginx_security_monitor.sh << 'EOF'
#!/bin/bash
# Nginx Security Monitor Script

LOG_FILE="/var/log/nginx/access.log"
SECURITY_LOG="/var/log/nginx/security.log"
MONITOR_SCRIPT="/app/nginx_monitor.py"

# Sprawdź czy logi istnieją
if [ ! -f "$LOG_FILE" ]; then
    echo "Error: Nginx access log not found at $LOG_FILE"
    exit 1
fi

# Uruchom monitor bezpieczeństwa
if [ -f "$MONITOR_SCRIPT" ]; then
    python3 "$MONITOR_SCRIPT" --log-file "$LOG_FILE" --lines 1000
else
    echo "Error: Security monitor script not found at $MONITOR_SCRIPT"
    exit 1
fi
EOF

chmod +x /usr/local/bin/nginx_security_monitor.sh

# Utwórz cron job do regularnego monitorowania
cat > /etc/cron.d/nginx-security << 'EOF'
# Nginx Security Monitoring
# Run every 5 minutes
*/5 * * * * root /usr/local/bin/nginx_security_monitor.sh >> /var/log/nginx/security.log 2>&1

# Clean old logs daily
0 2 * * * root find /var/log/nginx -name "*.log" -mtime +30 -delete
EOF

# Utwórz logrotate config dla nginx
cat > /etc/logrotate.d/nginx-security << 'EOF'
/var/log/nginx/access.log {
    daily
    missingok
    rotate 30
    compress
    delaycompress
    notifempty
    create 644 nginx nginx
    postrotate
        /bin/kill -USR1 `cat /var/run/nginx.pid 2>/dev/null` 2>/dev/null || true
    endscript
}

/var/log/nginx/error.log {
    daily
    missingok
    rotate 30
    compress
    delaycompress
    notifempty
    create 644 nginx nginx
    postrotate
        /bin/kill -USR1 `cat /var/run/nginx.pid 2>/dev/null` 2>/dev/null || true
    endscript
}

/var/log/nginx/security.log {
    daily
    missingok
    rotate 30
    compress
    delaycompress
    notifempty
    create 644 nginx nginx
}
EOF

# Sprawdź konfigurację nginx
echo "🔍 Testing nginx configuration..."
if nginx -t; then
    echo "✅ Nginx configuration is valid"
else
    echo "❌ Nginx configuration has errors"
    exit 1
fi

# Uruchom nginx
echo "🚀 Starting nginx..."
nginx -g "daemon off;" &

# Uruchom monitor bezpieczeństwa w tle
echo "🔍 Starting security monitor..."
python3 /app/nginx_monitor.py --realtime &

echo "✅ Nginx security setup completed!"
echo "📊 Monitor logs at: /var/log/nginx/security.log"
echo "🔒 Blocked IPs config: /etc/nginx/conf.d/security/blocked_ips.conf"
echo "📈 Security monitor: /usr/local/bin/nginx_security_monitor.sh"

# Keep container running
wait
