# Generated by Django 5.2.4 on 2026-02-20 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(db_index=True, max_length=1000, verbose_name='URL produktu')),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='ID produktu u producenta (np. z URL)', max_length=100, null=True, verbose_name='ID zewnętrzne')),
                ('name', models.CharField(max_length=500, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('image_url', models.URLField(blank=True, max_length=1000, verbose_name='URL obrazka')),
                ('scraped_at', models.DateTimeField(blank=True, null=True, verbose_name='Ostatni scrape')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Surowe dane')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produkt producenta',
                'verbose_name_plural': 'Produkty producenta',
                'db_table': 'producer_catalog_product',
                'ordering': ['source', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProducerSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('slug', models.SlugField(help_text='np. ava', unique=True, verbose_name='Slug')),
                ('base_url', models.URLField(max_length=500, verbose_name='URL bazowy')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Źródło producenta',
                'verbose_name_plural': 'Źródła producentów',
                'db_table': 'producer_catalog_source',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProducerProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=100, verbose_name='Rozmiar')),
                ('price_brutto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena brutto')),
                ('price_netto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena netto')),
                ('currency', models.CharField(default='PLN', max_length=10, verbose_name='Waluta')),
                ('stock_info', models.CharField(blank=True, max_length=100, verbose_name='Stan')),
                ('scraped_at', models.DateTimeField(blank=True, null=True, verbose_name='Ostatni scrape')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='producer_catalog.producerproduct', verbose_name='Produkt')),
            ],
            options={
                'verbose_name': 'Wariant producenta',
                'verbose_name_plural': 'Warianty producenta',
                'db_table': 'producer_catalog_variant',
                'ordering': ['product', 'size_name'],
                'unique_together': {('product', 'size_name')},
            },
        ),
        migrations.CreateModel(
            name='ProducerPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_brutto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena brutto')),
                ('price_netto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena netto')),
                ('currency', models.CharField(default='PLN', max_length=10, verbose_name='Waluta')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Zapisano')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='producer_catalog.producerproductvariant', verbose_name='Wariant')),
            ],
            options={
                'verbose_name': 'Historia ceny',
                'verbose_name_plural': 'Historia cen',
                'db_table': 'producer_catalog_price_history',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddField(
            model_name='producerproduct',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='producer_catalog.producersource', verbose_name='Źródło'),
        ),
        migrations.AlterUniqueTogether(
            name='producerproduct',
            unique_together={('source', 'url')},
        ),
    ]
