# Nowe tabele: tabu_product_detail, tabu_product_gallery, tabu_product_variant
# Usuwa: tabu_api_product, tabu_api_variant

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tabu', '0002_add_brand_category_to_tabuproduct'),
    ]

    operations = [
        migrations.DeleteModel(name='TabuProductVariant'),
        migrations.DeleteModel(name='TabuProduct'),
        migrations.CreateModel(
            name='TabuProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(db_index=True, help_text="Pole 'id' z API Tabu", unique=True)),
                ('symbol', models.CharField(db_index=True, max_length=100)),
                ('ean', models.CharField(blank=True, db_index=True, max_length=50)),
                ('name', models.CharField(max_length=500)),
                ('desc_short', models.TextField(blank=True, null=True)),
                ('desc_long', models.TextField(blank=True, help_text='Opis długi HTML', null=True)),
                ('desc_safety', models.TextField(blank=True, help_text='Informacje bezpieczeństwa', null=True)),
                ('category_path', models.CharField(blank=True, max_length=500)),
                ('api_category_id', models.IntegerField(db_index=True, default=0)),
                ('producer_name', models.CharField(blank=True, max_length=200)),
                ('api_producer_id', models.IntegerField(db_index=True, default=0)),
                ('producer_code', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True, help_text='Obraz główny', max_length=1000)),
                ('price_net', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_gross', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_old', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_kind', models.PositiveSmallIntegerField(default=1)),
                ('vat_label', models.CharField(default='23%', max_length=20)),
                ('vat_id', models.IntegerField(default=1)),
                ('vat_value', models.DecimalField(decimal_places=2, default=23, max_digits=5)),
                ('store_total', models.IntegerField(default=0)),
                ('unit_label', models.CharField(default='szt', max_length=50)),
                ('unit_id', models.IntegerField(default=1)),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('shipment', models.CharField(blank=True, max_length=200)),
                ('shipment_id', models.CharField(blank=True, max_length=50)),
                ('shipment_days', models.CharField(blank=True, max_length=50)),
                ('status_label', models.CharField(default='', max_length=50)),
                ('status_id', models.IntegerField(default=1)),
                ('status_auto', models.BooleanField(default=True)),
                ('url', models.URLField(default='https://tabu.com.pl/', max_length=1000)),
                ('version_signature', models.CharField(blank=True, max_length=100)),
                ('preorder', models.CharField(blank=True, max_length=50)),
                ('hidden_search', models.BooleanField(default=False)),
                ('last_update', models.DateTimeField()),
                ('promo', models.CharField(blank=True, max_length=100)),
                ('promo_uid', models.CharField(blank=True, max_length=100)),
                ('promo_from', models.DateTimeField(blank=True, null=True)),
                ('promo_to', models.DateTimeField(blank=True, null=True)),
                ('groups', models.JSONField(blank=True, default=list)),
                ('dictionaries', models.JSONField(blank=True, default=list, help_text='Atrybuty: Kolor, Rozmiar, Materiał...')),
                ('stores', models.JSONField(blank=True, default=list, help_text='[{id, store}]')),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('brand', models.ForeignKey(blank=True, db_column='tabu_brand_fk_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabu_products', to='tabu.brand')),
                ('category', models.ForeignKey(blank=True, db_column='tabu_category_fk_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabu_products', to='tabu.category')),
            ],
            options={
                'verbose_name': 'Tabu produkt (szczegóły)',
                'verbose_name_plural': 'Tabu produkty (szczegóły)',
                'db_table': 'tabu_product_detail',
            },
        ),
        migrations.AddIndex(model_name='tabuproduct', index=models.Index(fields=['api_id'], name='tabu_prod_d_api_id_idx')),
        migrations.AddIndex(model_name='tabuproduct', index=models.Index(fields=['symbol'], name='tabu_prod_d_symbol_idx')),
        migrations.AddIndex(model_name='tabuproduct', index=models.Index(fields=['api_category_id'], name='tabu_prod_d_api_cat_idx')),
        migrations.AddIndex(model_name='tabuproduct', index=models.Index(fields=['api_producer_id'], name='tabu_prod_d_api_prd_idx')),
        migrations.AddIndex(model_name='tabuproduct', index=models.Index(fields=['brand'], name='tabu_prod_d_brand_idx')),
        migrations.AddIndex(model_name='tabuproduct', index=models.Index(fields=['category'], name='tabu_prod_d_cat_idx')),
        migrations.CreateModel(
            name='TabuProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_image_id', models.IntegerField(db_index=True, help_text='id z gallery[]')),
                ('image_url', models.URLField(max_length=1000)),
                ('is_main', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='tabu.tabuproduct')),
            ],
            options={
                'verbose_name': 'Zdjęcie produktu Tabu',
                'verbose_name_plural': 'Zdjęcia produktów Tabu',
                'db_table': 'tabu_product_gallery',
                'ordering': ['order', 'api_image_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='tabuproductimage',
            constraint=models.UniqueConstraint(fields=('product', 'api_image_id'), name='tabu_prod_gal_prod_img_uniq'),
        ),
        migrations.CreateModel(
            name='TabuProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(db_index=True, help_text="Pole 'id' wariantu z API", unique=True)),
                ('symbol', models.CharField(db_index=True, max_length=120)),
                ('ean', models.CharField(blank=True, db_index=True, max_length=50)),
                ('price_net', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_gross', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_kind', models.PositiveSmallIntegerField(default=1)),
                ('vat_label', models.CharField(default='23%', max_length=20)),
                ('vat_id', models.IntegerField(default=1)),
                ('vat_value', models.DecimalField(decimal_places=2, default=23, max_digits=5)),
                ('store', models.IntegerField(db_index=True, default=0)),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('items', models.JSONField(blank=True, default=list, help_text='Parametry: Kolor, Rozmiar...')),
                ('stores', models.JSONField(blank=True, default=list, help_text='[{id, store}]')),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_variants', to='tabu.tabuproduct')),
            ],
            options={
                'verbose_name': 'Tabu wariant (API)',
                'verbose_name_plural': 'Tabu warianty (API)',
                'db_table': 'tabu_product_variant',
            },
        ),
        migrations.AddIndex(model_name='tabuproductvariant', index=models.Index(fields=['api_id'], name='tabu_prod_v_api_id_idx')),
        migrations.AddIndex(model_name='tabuproductvariant', index=models.Index(fields=['product'], name='tabu_prod_v_product_idx')),
        migrations.AddIndex(model_name='tabuproductvariant', index=models.Index(fields=['ean'], name='tabu_prod_v_ean_idx')),
        migrations.AddIndex(model_name='tabuproductvariant', index=models.Index(fields=['store'], name='tabu_prod_v_store_idx')),
    ]
