# Generated by Django 5.2.4 on 2026-02-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabu', '0004_remove_old_product_models'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tabuproductimage',
            name='tabu_prod_gal_prod_img_uniq',
        ),
        migrations.RenameIndex(
            model_name='tabuproduct',
            new_name='tabu_produc_api_id_7b3247_idx',
            old_name='tabu_prod_d_api_id_idx',
        ),
        migrations.RenameIndex(
            model_name='tabuproduct',
            new_name='tabu_produc_symbol_964b5d_idx',
            old_name='tabu_prod_d_symbol_idx',
        ),
        migrations.RenameIndex(
            model_name='tabuproduct',
            new_name='tabu_produc_api_cat_43517d_idx',
            old_name='tabu_prod_d_api_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='tabuproduct',
            new_name='tabu_produc_api_pro_8a8b86_idx',
            old_name='tabu_prod_d_api_prd_idx',
        ),
        migrations.RenameIndex(
            model_name='tabuproduct',
            new_name='tabu_produc_tabu_br_fde65b_idx',
            old_name='tabu_prod_d_brand_idx',
        ),
        migrations.RenameIndex(
            model_name='tabuproduct',
            new_name='tabu_produc_tabu_ca_763753_idx',
            old_name='tabu_prod_d_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='tabuproductvariant',
            new_name='tabu_produc_api_id_f3823c_idx',
            old_name='tabu_prod_v_api_id_idx',
        ),
        migrations.RenameIndex(
            model_name='tabuproductvariant',
            new_name='tabu_produc_product_32b9c5_idx',
            old_name='tabu_prod_v_product_idx',
        ),
        migrations.RenameIndex(
            model_name='tabuproductvariant',
            new_name='tabu_produc_ean_9bce7e_idx',
            old_name='tabu_prod_v_ean_idx',
        ),
        migrations.RenameIndex(
            model_name='tabuproductvariant',
            new_name='tabu_produc_store_43f8f0_idx',
            old_name='tabu_prod_v_store_idx',
        ),
        migrations.AlterUniqueTogether(
            name='tabuproductimage',
            unique_together={('product', 'api_image_id')},
        ),
        migrations.AddIndex(
            model_name='tabuproductimage',
            index=models.Index(fields=['product'], name='tabu_produc_product_7132ff_idx'),
        ),
    ]
