# Generated by Django 5.2.4 on 2026-02-09 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabu', '0005_remove_tabuproductimage_tabu_prod_gal_prod_img_uniq_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabuproduct',
            options={'ordering': ['-api_id'], 'verbose_name': 'Tabu produkt (szczegóły)', 'verbose_name_plural': 'Tabu produkty (szczegóły)'},
        ),
    ]
