# Generated by Django 5.2.4 on 2026-02-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabu', '0006_alter_tabuproduct_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_api_id', models.IntegerField(db_index=True, help_text='ID wariantu z API Tabu')),
                ('product_api_id', models.IntegerField(db_index=True, help_text='ID produktu z API Tabu')),
                ('product_name', models.CharField(blank=True, max_length=500, null=True)),
                ('variant_symbol', models.CharField(blank=True, max_length=120, null=True)),
                ('old_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('new_stock', models.PositiveIntegerField(blank=True, null=True)),
                ('stock_change', models.IntegerField(blank=True, null=True)),
                ('change_type', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historia stanów magazynowych',
                'verbose_name_plural': 'Historia stanów magazynowych',
                'db_table': 'tabu_stock_history',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['variant_api_id'], name='tabu_sh_variant_idx'), models.Index(fields=['product_api_id'], name='tabu_sh_product_idx'), models.Index(fields=['timestamp'], name='tabu_sh_timestamp_idx'), models.Index(fields=['change_type'], name='tabu_sh_change_idx'), models.Index(fields=['product_api_id', 'timestamp'], name='tabu_sh_prod_time_idx')],
            },
        ),
    ]
