# Generated by Django 5.2.4 on 2026-02-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabu', '0009_tabuproductvariant_mapped_variant_uid'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tabuproductvariant',
            new_name='tabu_produc_mapped__567a04_idx',
            old_name='tabu_produ_mapped__idx',
        ),
    ]
