# Generated by Django 5.2.4 on 2026-07-24 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabu', '0010_rename_tabu_produ_mapped__idx_tabu_produc_mapped__567a04_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tabuproduct',
            options={'ordering': ['-api_id'], 'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkty'},
        ),
        migrations.AlterModelOptions(
            name='tabuproductimage',
            options={'ordering': ['order', 'api_image_id'], 'verbose_name': 'Obraz produktu', 'verbose_name_plural': 'Obrazy produktów'},
        ),
        migrations.AlterModelOptions(
            name='tabuproductvariant',
            options={'verbose_name': 'Wariant produktu', 'verbose_name_plural': 'Warianty produktów'},
        ),
    ]
