# Generated by Django 5.2.4 on 2026-07-24 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabu', '0011_alter_tabuproduct_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saga_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('saga_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('compensating', 'Compensating'), ('compensated', 'Compensated')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('total_steps', models.IntegerField(default=0)),
                ('completed_steps', models.IntegerField(default=0)),
                ('failed_step', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Saga Log',
                'verbose_name_plural': 'Saga Logs',
                'db_table': 'tabu_saga_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SagaStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=100)),
                ('step_order', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('compensating', 'Compensating'), ('compensated', 'Compensated')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('compensated_at', models.DateTimeField(blank=True, null=True)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('compensation_attempted', models.BooleanField(default=False)),
                ('compensation_successful', models.BooleanField(default=False)),
                ('saga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='tabu.saga')),
            ],
            options={
                'verbose_name': 'Saga Step',
                'verbose_name_plural': 'Saga Steps',
                'db_table': 'tabu_saga_steps',
                'ordering': ['saga', 'step_order'],
                'unique_together': {('saga', 'step_order')},
            },
        ),
    ]
