# Generated by Django 5.2 on 2025-05-21 07:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAndPrices',
            fields=[
                ('product_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('current_stock', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stan magazynowy',
                'verbose_name_plural': 'Stany magazynowe',
                'db_table': 'stock_and_prices',
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_stock', models.IntegerField()),
                ('new_stock', models.IntegerField()),
                ('change_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('change_reason', models.CharField(blank=True, max_length=255)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='main.stockandprices')),
            ],
            options={
                'verbose_name': 'Historia stanu magazynowego',
                'verbose_name_plural': 'Historia stanów magazynowych',
                'db_table': 'stock_history',
                'ordering': ['-change_date'],
            },
        ),
    ]
