# Generated by Django 5.2.4 on 2026-07-28 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saga_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('saga_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('compensating', 'Compensating'), ('compensated', 'Compensated')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('total_steps', models.IntegerField(default=0)),
                ('completed_steps', models.IntegerField(default=0)),
                ('failed_step', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Saga Log',
                'verbose_name_plural': 'Saga Logs',
                'db_table': 'mada_saga_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApiSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('full_import', 'Import pełny'), ('partial_import', 'Import przyrostowy')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('running', 'W trakcie'), ('completed', 'Zakończone'), ('failed', 'Błąd')], db_index=True, default='pending', max_length=20)),
                ('file_name', models.CharField(blank=True, help_text='Nazwa pliku z manifestu Mada (np. 2026-07-28-full lub 2026-07-28_114003)', max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('products_processed', models.IntegerField(default=0)),
                ('products_created', models.IntegerField(default=0)),
                ('products_updated', models.IntegerField(default=0)),
                ('products_failed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log synchronizacji API',
                'verbose_name_plural': 'Logi synchronizacji API',
                'db_table': 'mada_apisynclog',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['sync_type'], name='mada_asl_sync_type_idx'), models.Index(fields=['status'], name='mada_asl_status_idx'), models.Index(fields=['started_at'], name='mada_asl_started_idx'), models.Index(fields=['file_name'], name='mada_asl_file_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Marki',
                'db_table': 'mada_brand',
                'indexes': [models.Index(fields=['producer_id'], name='mada_brand_producer_id_idx'), models.Index(fields=['name'], name='mada_brand_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mada.category')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
                'db_table': 'mada_category',
            },
        ),
        migrations.CreateModel(
            name='MadaProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(db_index=True, help_text="Pole 'ID' produktu z feedu Mada", unique=True)),
                ('name', models.CharField(max_length=500)),
                ('desc', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vat', models.DecimalField(decimal_places=2, default=23, max_digits=5)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False gdy produkt zniknął z ostatniego pełnego importu (wygaszony)')),
                ('mapped_product_uid', models.IntegerField(blank=True, db_index=True, help_text='ID produktu w bazie MPD', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_api_sync', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(blank=True, db_column='mada_brand_fk_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mada_products', to='mada.brand')),
                ('category', models.ForeignKey(blank=True, db_column='mada_category_fk_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mada_products', to='mada.category')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
                'db_table': 'mada_product',
                'ordering': ['-api_id'],
            },
        ),
        migrations.CreateModel(
            name='MadaProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_image_id', models.CharField(db_index=True, help_text='atrybut id z IMG', max_length=50)),
                ('image_url', models.URLField(max_length=1000)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mada.madaproduct')),
            ],
            options={
                'verbose_name': 'Obraz produktu',
                'verbose_name_plural': 'Obrazy produktów',
                'db_table': 'mada_product_image',
                'ordering': ['order', 'api_image_id'],
            },
        ),
        migrations.CreateModel(
            name='MadaProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_key', models.CharField(db_index=True, max_length=255)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('ean', models.CharField(blank=True, db_index=True, max_length=50)),
                ('stock', models.IntegerField(default=0)),
                ('mapped_variant_uid', models.IntegerField(blank=True, db_index=True, help_text='ID wariantu w bazie MPD (variant_id)', null=True)),
                ('is_mapped', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='mada.madaproduct')),
            ],
            options={
                'verbose_name': 'Wariant produktu',
                'verbose_name_plural': 'Warianty produktów',
                'db_table': 'mada_product_variant',
            },
        ),
        migrations.CreateModel(
            name='SagaStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=100)),
                ('step_order', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('compensating', 'Compensating'), ('compensated', 'Compensated')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('compensated_at', models.DateTimeField(blank=True, null=True)),
                ('input_data', models.JSONField(blank=True, default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('compensation_attempted', models.BooleanField(default=False)),
                ('compensation_successful', models.BooleanField(default=False)),
                ('saga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='mada.saga')),
            ],
            options={
                'verbose_name': 'Saga Step',
                'verbose_name_plural': 'Saga Steps',
                'db_table': 'mada_saga_steps',
                'ordering': ['saga', 'step_order'],
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_api_id', models.IntegerField(db_index=True, help_text='ID produktu z feedu Mada')),
                ('variant_key', models.CharField(blank=True, max_length=255, null=True)),
                ('product_name', models.CharField(blank=True, max_length=500, null=True)),
                ('variant_label', models.CharField(blank=True, help_text='kolor/rozmiar', max_length=150, null=True)),
                ('old_stock', models.IntegerField(blank=True, null=True)),
                ('new_stock', models.IntegerField(blank=True, null=True)),
                ('stock_change', models.IntegerField(blank=True, null=True)),
                ('change_type', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historia stanów magazynowych',
                'verbose_name_plural': 'Historia stanów magazynowych',
                'db_table': 'mada_stock_history',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['product_api_id'], name='mada_sh_product_idx'), models.Index(fields=['variant_key'], name='mada_sh_variant_idx'), models.Index(fields=['timestamp'], name='mada_sh_timestamp_idx'), models.Index(fields=['change_type'], name='mada_sh_change_idx'), models.Index(fields=['product_api_id', 'timestamp'], name='mada_sh_prod_time_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category_id'], name='mada_category_category_id_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='mada_category_name_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='mada_category_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='madaproduct',
            index=models.Index(fields=['api_id'], name='mada_produc_api_id_b218d6_idx'),
        ),
        migrations.AddIndex(
            model_name='madaproduct',
            index=models.Index(fields=['brand'], name='mada_produc_mada_br_062de4_idx'),
        ),
        migrations.AddIndex(
            model_name='madaproduct',
            index=models.Index(fields=['category'], name='mada_produc_mada_ca_b22a23_idx'),
        ),
        migrations.AddIndex(
            model_name='madaproduct',
            index=models.Index(fields=['is_active'], name='mada_produc_is_acti_46f90f_idx'),
        ),
        migrations.AddIndex(
            model_name='madaproduct',
            index=models.Index(fields=['mapped_product_uid'], name='mada_produc_mapped__d1a386_idx'),
        ),
        migrations.AddIndex(
            model_name='madaproductimage',
            index=models.Index(fields=['product'], name='mada_produc_product_c369a5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='madaproductimage',
            unique_together={('product', 'api_image_id')},
        ),
        migrations.AddIndex(
            model_name='madaproductvariant',
            index=models.Index(fields=['product'], name='mada_produc_product_013687_idx'),
        ),
        migrations.AddIndex(
            model_name='madaproductvariant',
            index=models.Index(fields=['ean'], name='mada_produc_ean_24ff94_idx'),
        ),
        migrations.AddIndex(
            model_name='madaproductvariant',
            index=models.Index(fields=['variant_key'], name='mada_produc_variant_a5ac65_idx'),
        ),
        migrations.AddIndex(
            model_name='madaproductvariant',
            index=models.Index(fields=['mapped_variant_uid'], name='mada_produc_mapped__8f6c07_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='madaproductvariant',
            unique_together={('product', 'variant_key')},
        ),
        migrations.AlterUniqueTogether(
            name='sagastep',
            unique_together={('saga', 'step_order')},
        ),
    ]
