# Generated by Django 5.2.4 on 2025-09-27 09:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Attribute',
                'verbose_name_plural': 'Attributes',
                'db_table': 'attributes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('opis', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('iai_brand_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'brands',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
                'db_table': 'categories',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FabricComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'fabric_component',
            },
        ),
        migrations.CreateModel(
            name='FullChangeFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bucket_url', models.URLField(blank=True, null=True)),
                ('local_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Plik XML',
                'verbose_name_plural': 'Pliki XML',
                'db_table': 'full_change_files',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IaiProductCounter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('counter_value', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Licznik IAI Product ID',
                'verbose_name_plural': 'Liczniki IAI Product ID',
                'db_table': 'iai_product_counter',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Paths',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_id', models.BigIntegerField(blank=True, null=True)),
                ('iai_category_id', models.IntegerField(blank=True, null=True)),
                ('iai_menu_id', models.IntegerField(blank=True, null=True)),
                ('iai_menu_parent_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ścieżka',
                'verbose_name_plural': 'Ścieżki',
                'db_table': 'path',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductSeries',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Seria',
                'verbose_name_plural': 'Serie',
                'db_table': 'product_series',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductSetItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_set_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Set Item',
                'verbose_name_plural': 'Product Set Items',
                'db_table': 'product_set_items',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductVariants',
            fields=[
                ('variant_id', models.AutoField(db_column='variant_id', primary_key=True, serialize=False)),
                ('producer_code', models.CharField(blank=True, max_length=255, null=True)),
                ('iai_product_id', models.IntegerField(blank=True, null=True)),
                ('exported_to_iai', models.BooleanField(default=False, verbose_name='Wyeksportowany do IAI')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'db_table': 'product_variants',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('name_lower', models.CharField(blank=True, max_length=255, null=True)),
                ('iai_size_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
                'db_table': 'sizes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('long_name', models.CharField(blank=True, max_length=255, null=True)),
                ('short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('showcase_image', models.URLField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('tel', models.CharField(blank=True, max_length=50, null=True)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('www', models.URLField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
                'db_table': 'sources',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('stock_id', models.BigIntegerField()),
                ('source_id', models.BigIntegerField(blank=True, null=True)),
                ('previous_stock', models.IntegerField()),
                ('new_stock', models.IntegerField()),
                ('previous_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('new_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('change_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Historia stanu magazynowego',
                'verbose_name_plural': 'Historia stanów magazynowych',
                'db_table': 'stock_history',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit_id', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Jednostka',
                'verbose_name_plural': 'Jednostki',
                'db_table': 'units',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vat_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'vat',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('hex_code', models.CharField(blank=True, max_length=7, null=True)),
                ('iai_colors_id', models.IntegerField(blank=True, null=True)),
                ('parent_id', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='MPD.colors')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'db_table': 'colors',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductPaths',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('path_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Ścieżka produktu',
                'verbose_name_plural': 'Ścieżki produktów',
                'db_table': 'product_path',
                'managed': True,
                'unique_together': {('product_id', 'path_id')},
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('short_description', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('visibility', models.BooleanField(default=True, verbose_name='Widoczność w sklepie')),
                ('brand', models.ForeignKey(blank=True, db_column='brand_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='MPD.brands')),
                ('series', models.ForeignKey(blank=True, db_column='series_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MPD.productseries')),
                ('unit', models.ForeignKey(blank=True, db_column='unit', null=True, on_delete=django.db.models.deletion.CASCADE, to='MPD.units', to_field='unit_id')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('iai_product_id', models.IntegerField(blank=True, null=True)),
                ('file_path', models.CharField(max_length=500)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='MPD.products')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'db_table': 'product_images',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mapped_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sets', to='MPD.products')),
            ],
            options={
                'verbose_name': 'Product Set',
                'verbose_name_plural': 'Product Sets',
                'db_table': 'product_set',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductVariantsRetailPrice',
            fields=[
                ('variant', models.OneToOneField(db_column='variant_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='MPD.productvariants')),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('net_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'product_variants_retail_price',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='productvariants',
            name='color',
            field=models.ForeignKey(blank=True, db_column='color_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='MPD.colors'),
        ),
        migrations.AddField(
            model_name='productvariants',
            name='producer_color',
            field=models.ForeignKey(blank=True, db_column='producer_color_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producer_variants', to='MPD.colors'),
        ),
        migrations.AddField(
            model_name='productvariants',
            name='product',
            field=models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='MPD.products'),
        ),
        migrations.AddField(
            model_name='productvariants',
            name='size',
            field=models.ForeignKey(blank=True, db_column='size_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='MPD.sizes'),
        ),
        migrations.CreateModel(
            name='ProductvariantsSources',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ean', models.CharField(blank=True, max_length=50, null=True)),
                ('variant_uid', models.IntegerField(blank=True, null=True)),
                ('gtin14', models.CharField(blank=True, max_length=50, null=True)),
                ('gtin13', models.CharField(blank=True, max_length=50, null=True)),
                ('gtin12', models.CharField(blank=True, max_length=50, null=True)),
                ('isbn10', models.CharField(blank=True, max_length=50, null=True)),
                ('gtin8', models.CharField(blank=True, max_length=50, null=True)),
                ('upce', models.CharField(blank=True, max_length=50, null=True)),
                ('mpn', models.CharField(blank=True, max_length=50, null=True)),
                ('other', models.CharField(blank=True, max_length=50, null=True)),
                ('variant', models.ForeignKey(db_column='variant_id', on_delete=django.db.models.deletion.CASCADE, to='MPD.productvariants')),
                ('source', models.ForeignKey(blank=True, db_column='source_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='MPD.sources')),
            ],
            options={
                'verbose_name': 'Product Variant Source',
                'verbose_name_plural': 'Product Variant Sources',
                'db_table': 'product_variants_sources',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StockAndPrices',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('last_updated', models.DateTimeField()),
                ('source', models.ForeignKey(db_column='source_id', on_delete=django.db.models.deletion.CASCADE, to='MPD.sources')),
                ('variant', models.ForeignKey(db_column='variant_id', on_delete=django.db.models.deletion.CASCADE, to='MPD.productvariants')),
            ],
            options={
                'verbose_name': 'Stan magazynowy',
                'verbose_name_plural': 'Stany magazynowe',
                'db_table': 'stock_and_prices',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductFabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveSmallIntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MPD.fabriccomponent')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabrics', to='MPD.products')),
            ],
            options={
                'db_table': 'product_fabric',
                'unique_together': {('product', 'component')},
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MPD.attributes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='MPD.products')),
            ],
            options={
                'verbose_name': 'Atrybut produktu',
                'verbose_name_plural': 'Atrybuty produktów',
                'db_table': 'product_attributes',
                'managed': True,
                'unique_together': {('product', 'attribute')},
            },
        ),
    ]
