# Generated by Django 5.2.4 on 2026-02-14 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0002_alter_stockhistory_change_date_alter_stockhistory_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Sezon',
                'verbose_name_plural': 'Sezony',
                'db_table': 'seasons',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='products',
            name='season',
            field=models.ForeignKey(blank=True, db_column='season_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='MPD.seasons', verbose_name='Sezon'),
        ),
    ]
