# Generated by Django 5.2.4 on 2026-02-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0007_remove_productvariants_producer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariantssources',
            name='variant_uid',
            field=models.IntegerField(blank=True, help_text='Identyfikator wariantu w hurtowni: np. dla Tabu = api_id z tabu_product_variant.', null=True),
        ),
    ]
