# Generated by Django 5.2.4 on 2026-02-21 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0008_alter_productvariantssources_variant_uid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productseries',
            options={'managed': True, 'ordering': ['brand', 'name'], 'verbose_name': 'Seria', 'verbose_name_plural': 'Serie'},
        ),
        migrations.AddField(
            model_name='productseries',
            name='brand',
            field=models.ForeignKey(blank=True, db_column='brand_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='MPD.brands', verbose_name='Marka'),
        ),
        migrations.AlterUniqueTogether(
            name='productseries',
            unique_together={('brand', 'name')},
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('brand', models.ForeignKey(db_column='brand_id', on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='MPD.brands', verbose_name='Marka')),
            ],
            options={
                'verbose_name': 'Kolekcja',
                'verbose_name_plural': 'Kolekcje',
                'db_table': 'collections',
                'ordering': ['brand', 'sort_order', 'name'],
                'managed': True,
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.AddField(
            model_name='products',
            name='collection',
            field=models.ForeignKey(blank=True, db_column='collection_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='MPD.collection', verbose_name='Kolekcja'),
        ),
    ]
