# Generated by Django 5.2.4 on 2026-03-10 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0009_collection_and_series_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='iai_product_id',
        ),
        migrations.RemoveField(
            model_name='productvariants',
            name='iai_product_id',
        ),
    ]
