# Generated by Django 5.2.4 on 2026-03-10 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0009_collection_and_series_brand'),
    ]

    operations = [
        # DROP COLUMN IF EXISTS - idempotentne (druga gałąź migracji mogła już usunąć)
        migrations.RunSQL(
            sql="ALTER TABLE product_images DROP COLUMN IF EXISTS iai_product_id;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE product_variants DROP COLUMN IF EXISTS iai_product_id;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
