# Generated by Django 5.2.4 on 2026-03-10 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0009_collection_and_series_brand'),
    ]

    operations = [
        # RunSQL z IF EXISTS - idempotentne (druga gałąź mogła już usunąć kolumny).
        # Uwaga: RunSQL nie aktualizuje stanu Django, ale w tym merge obie gałęzie
        # usuwały te pola - stan jest ustawiony przez 0010_remove_productimage (RemoveField
        # w 0009 dla productvariants, RunSQL dla product_images) lub przez kolejność aplikowania.
        migrations.RunSQL(
            sql="ALTER TABLE product_images DROP COLUMN IF EXISTS iai_product_id;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE product_variants DROP COLUMN IF EXISTS iai_product_id;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
