# Generated by Django 5.2.4 on 2026-03-17 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0010_remove_productimage_iai_product_id'),
        ('MPD', '0010_remove_productimage_iai_product_id_and_more'),
    ]

    operations = [
    ]
