# Generated by Django 5.2.4 on 2026-03-17 11:57

from django.db import migrations


class Migration(migrations.Migration):
    """
    Usunięcie kolumny iai_product_id z product_images.

    Używamy RunSQL z DROP COLUMN IF EXISTS, żeby migracja była bezpieczna
    gdy kolumna została już usunięta wcześniej (np. przez 0010_* gałąź).
    """

    dependencies = [
        ("MPD", "0011_merge_20260317_1249"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE product_images
                DROP COLUMN IF EXISTS iai_product_id;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
