# Generated by Django 5.2.4 on 2026-03-18 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0012_remove_productimage_iai_product_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IaiProductCounter',
        ),
    ]
