# Generated by Django 5.2.4 on 2026-03-19 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0013_delete_iaiproductcounter'),
    ]

    operations = [
        # RunSQL z IF EXISTS – kolumny mogły być już usunięte przez wcześniejsze migracje
        # (0010_remove_productimage_iai_product_id_and_more, 0012_remove_productimage_iai_product_id).
        migrations.RunSQL(
            sql="ALTER TABLE product_images DROP COLUMN IF EXISTS iai_product_id;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="ALTER TABLE product_variants DROP COLUMN IF EXISTS iai_product_id;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
