# Generated by Django 5.2.4 on 2026-07-14 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0015_fix_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabriccomponent',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productfabric',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='iai_product_id',
        ),
        migrations.RemoveField(
            model_name='productvariants',
            name='iai_product_id',
        ),
    ]
