# Generated by Django 5.2.4 on 2026-07-14 08:05

from django.db import migrations

from ._legacy_pk_utils import drop_column_if_exists


def remove_legacy_iai_product_id_columns(apps, schema_editor):
    drop_column_if_exists(schema_editor, 'product_images', 'iai_product_id')
    drop_column_if_exists(schema_editor, 'product_variants', 'iai_product_id')


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0015_fix_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabriccomponent',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productfabric',
            options={'managed': True},
        ),
        migrations.RunPython(
            remove_legacy_iai_product_id_columns,
            migrations.RunPython.noop,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='productimage',
                    name='iai_product_id',
                ),
                migrations.RemoveField(
                    model_name='productvariants',
                    name='iai_product_id',
                ),
            ],
        ),
    ]
