# Generated by Django 5.2.4 on 2026-07-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0016_alter_fabriccomponent_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariantssources',
            unique_together={('variant', 'source')},
        ),
        migrations.AlterUniqueTogether(
            name='stockandprices',
            unique_together={('variant', 'source')},
        ),
    ]
