# Generated by Django 6.0.7 on 2026-08-29 10:28

import django.db.models.deletion
from django.db import migrations, models


def _normalize_color_key(name: str) -> str:
    return (name or '').lower().replace('/', '_').replace(' ', '_')


def _basename_lower(file_path: str) -> str:
    parts = (file_path or '').replace('\\', '/').split('/')
    return (parts[-1] or file_path or '').lower()


def backfill_producer_color(apps, schema_editor):
    """
    Uzupełnia productimage.producer_color_id dla istniejących zdjęć tą samą heurystyką
    co front (groupImagesByColor): dopasowanie nazwy koloru w basename file_path —
    najpierw kolor producenta, potem zwykły kolor, dłuższe nazwy pierwsze.
    """
    db = schema_editor.connection.alias
    ProductImage = apps.get_model('MPD', 'ProductImage')
    ProductVariants = apps.get_model('MPD', 'ProductVariants')

    images = list(ProductImage.objects.using(db).all())
    product_ids = {img.product_id for img in images}
    if not product_ids:
        return

    keys_by_product = {}
    variants = (
        ProductVariants.objects.using(db)
        .filter(product_id__in=product_ids)
        .values('product_id', 'color_id', 'color__name', 'producer_color_id', 'producer_color__name')
    )
    for v in variants:
        entry = keys_by_product.setdefault(v['product_id'], {'producer': {}, 'color': {}})
        if v['producer_color_id'] and v['producer_color__name']:
            entry['producer'][v['producer_color_id']] = _normalize_color_key(v['producer_color__name'])
        if v['color_id'] and v['color__name']:
            entry['color'][v['color_id']] = _normalize_color_key(v['color__name'])

    to_update = []
    for img in images:
        if img.producer_color_id:
            continue
        entry = keys_by_product.get(img.product_id)
        if not entry:
            continue
        file_name = _basename_lower(img.file_path)
        producer = sorted(entry['producer'].items(), key=lambda kv: -len(kv[1]))
        color = sorted(entry['color'].items(), key=lambda kv: -len(kv[1]))
        matched = None
        for cid, key in producer:
            if key and key in file_name:
                matched = cid
                break
        if matched is None:
            for cid, key in color:
                if key and key in file_name:
                    matched = cid
                    break
        if matched is not None:
            img.producer_color_id = matched
            to_update.append(img)

    if to_update:
        ProductImage.objects.using(db).bulk_update(to_update, ['producer_color_id'], batch_size=500)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        # Niezależne od 0018–0020 (Sources.type / path unique) — inna tabela.
        # Przy scaleniu gałęzi zrobić `makemigrations --merge`.
        ('MPD', '0017_alter_productvariantssources_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='origin_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='productimage',
            name='producer_color',
            field=models.ForeignKey(blank=True, db_column='producer_color_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_images', to='MPD.colors'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='source',
            field=models.ForeignKey(blank=True, db_column='source_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_images', to='MPD.sources'),
        ),
        migrations.RunPython(backfill_producer_color, noop_reverse),
    ]
