# Generated by Django 6.0.7 on 2026-08-29 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0020_drop_path_name_unique'),
        ('MPD', '0021_product_image_color_source'),
    ]

    operations = [
    ]
