# Generated by Django 6.0.7 on 2026-08-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0023_colors_name_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='presta_manufacturer_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID producenta w PrestaShop'),
        ),
        migrations.AddField(
            model_name='colors',
            name='presta_option_value_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID product_option_value w PrestaShop (grupa "Kolor")'),
        ),
        migrations.AddField(
            model_name='paths',
            name='presta_category_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID kategorii w PrestaShop'),
        ),
        migrations.AddField(
            model_name='products',
            name='presta_product_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID produktu w PrestaShop'),
        ),
        migrations.AddField(
            model_name='productvariants',
            name='presta_combination_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID combination w PrestaShop'),
        ),
        migrations.AddField(
            model_name='sizes',
            name='presta_option_value_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID product_option_value w PrestaShop (grupa "Rozmiar")'),
        ),
    ]
