# Generated by Django 5.2.4 on 2026-07-24 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matterhorn1', '0005_alter_productimage_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saga',
            options={'ordering': ['-created_at'], 'verbose_name': 'Saga', 'verbose_name_plural': 'Sagi'},
        ),
        migrations.AlterModelOptions(
            name='sagastep',
            options={'ordering': ['saga', 'step_order'], 'verbose_name': 'Krok sagi', 'verbose_name_plural': 'Kroki sagi'},
        ),
    ]
