# Generated by Django 5.2.4 on 2026-07-24 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matterhorn1', '0006_alter_saga_options_alter_sagastep_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saga',
            options={'ordering': ['-created_at'], 'verbose_name': 'Saga', 'verbose_name_plural': 'Saga'},
        ),
    ]
