# Generated by Django 5.2.4 on 2026-07-24 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matterhorn1', '0007_alter_saga_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saga',
            options={'ordering': ['-created_at'], 'verbose_name': 'Saga Log', 'verbose_name_plural': 'Saga Logs'},
        ),
        migrations.AlterModelOptions(
            name='sagastep',
            options={'ordering': ['saga', 'step_order'], 'verbose_name': 'Saga Step', 'verbose_name_plural': 'Saga Steps'},
        ),
    ]
