# Generated by Django 5.2.4 on 2026-01-01 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_filter', models.BooleanField(default=False, help_text='Czy kategoria jest filtrem (nie kategorią w menu)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Kategoria nadrzędna', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='wega.category')),
            ],
            options={
                'verbose_name': 'Kategoria WEGA',
                'verbose_name_plural': 'Kategorie WEGA',
                'db_table': 'wega_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('gprs', models.TextField(blank=True, help_text='Dane GPRS (wymóg unijny)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dostawca WEGA',
                'verbose_name_plural': 'Dostawcy WEGA',
                'db_table': 'wega_manufacturer',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['manufacturer_id'], name='wega_manufa_manufac_9c012c_idx'), models.Index(fields=['name'], name='wega_manufa_name_ea2f65_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(db_index=True, unique=True)),
                ('url', models.URLField(blank=True, max_length=1000, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Cena netto produktu', max_digits=10)),
                ('gross_price', models.DecimalField(decimal_places=2, help_text='Cena brutto produktu', max_digits=10)),
                ('symbol', models.IntegerField(blank=True, null=True)),
                ('is_new', models.BooleanField(default=False, help_text='Czy produkt jest nowością')),
                ('is_promotion', models.BooleanField(default=False, help_text='Czy produkt jest w promocji')),
                ('pcs_in_a_box', models.IntegerField(blank=True, help_text='Ile sztuk jest w jednym opakowaniu', null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Opis produktu', max_length=1500, null=True)),
                ('material', models.CharField(blank=True, help_text='Skład produktu', max_length=500, null=True)),
                ('size_chart', models.URLField(blank=True, help_text='Link do obrazu z tabelą rozmiarów', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_api_sync', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, help_text='Kategoria produktu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='wega.category')),
                ('manufacturer', models.ForeignKey(blank=True, help_text='Producent/dostawca', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='wega.manufacturer')),
            ],
            options={
                'verbose_name': 'Produkt WEGA',
                'verbose_name_plural': 'Produkty WEGA',
                'db_table': 'wega_product',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(help_text='Data rozpoczęcia nowości')),
                ('end_date', models.DateTimeField(help_text='Data zakończenia nowości')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_product', to='wega.product')),
            ],
            options={
                'verbose_name': 'Nowość WEGA',
                'verbose_name_plural': 'Nowości WEGA',
                'db_table': 'wega_new',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('available', models.IntegerField(default=0, help_text='Liczba reprezentująca stan magazynowy')),
                ('ean', models.CharField(blank=True, db_index=True, help_text='Kod EAN produktu', max_length=25, null=True)),
                ('color_image_url', models.URLField(blank=True, help_text='Adres obrazu reprezentujący kolor atrybutu', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='wega.product')),
            ],
            options={
                'verbose_name': 'Atrybut produktu WEGA',
                'verbose_name_plural': 'Atrybuty produktów WEGA',
                'db_table': 'wega_productattribute',
                'ordering': ['product', 'size', 'color'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255)),
                ('is_main', models.BooleanField(default=False, help_text='Czy to główny obraz produktu')),
                ('order', models.PositiveIntegerField(default=0, help_text='Kolejność wyświetlania')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wega.product')),
            ],
            options={
                'verbose_name': 'Obraz produktu WEGA',
                'verbose_name_plural': 'Obrazy produktów WEGA',
                'db_table': 'wega_productimage',
                'ordering': ['-is_main', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(help_text='Data rozpoczęcia promocji')),
                ('end_date', models.DateTimeField(help_text='Data zakończenia promocji')),
                ('value', models.DecimalField(decimal_places=2, help_text='Wartość procentowa promocji', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='wega.product')),
            ],
            options={
                'verbose_name': 'Promocja WEGA',
                'verbose_name_plural': 'Promocje WEGA',
                'db_table': 'wega_promotion',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='RelatedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_product_id', models.IntegerField(help_text='ID produktu powiązanego')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='wega.product')),
            ],
            options={
                'verbose_name': 'Powiązany produkt WEGA',
                'verbose_name_plural': 'Powiązane produkty WEGA',
                'db_table': 'wega_relatedproduct',
                'ordering': ['product', 'related_product_id'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category_id'], name='wega_catego_categor_9083c4_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='wega_catego_parent__2f345f_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_filter'], name='wega_catego_is_filt_88a029_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_id'], name='wega_produc_product_1d2c80_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['symbol'], name='wega_produc_symbol_4babfe_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='wega_produc_categor_a77e54_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['manufacturer'], name='wega_produc_manufac_6be585_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_new'], name='wega_produc_is_new_f00b87_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_promotion'], name='wega_produc_is_prom_31517b_idx'),
        ),
        migrations.AddIndex(
            model_name='new',
            index=models.Index(fields=['product'], name='wega_new_product_84f84b_idx'),
        ),
        migrations.AddIndex(
            model_name='new',
            index=models.Index(fields=['start_date', 'end_date'], name='wega_new_start_d_7c7b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='productattribute',
            index=models.Index(fields=['product'], name='wega_produc_product_9ac175_idx'),
        ),
        migrations.AddIndex(
            model_name='productattribute',
            index=models.Index(fields=['ean'], name='wega_produc_ean_b9ec62_idx'),
        ),
        migrations.AddIndex(
            model_name='productattribute',
            index=models.Index(fields=['size'], name='wega_produc_size_8b6376_idx'),
        ),
        migrations.AddIndex(
            model_name='productattribute',
            index=models.Index(fields=['color'], name='wega_produc_color_16041b_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product'], name='wega_produc_product_321e64_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['is_main'], name='wega_produc_is_main_943145_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['product'], name='wega_promot_product_ffb8eb_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['start_date', 'end_date'], name='wega_promot_start_d_73e6e5_idx'),
        ),
        migrations.AddIndex(
            model_name='relatedproduct',
            index=models.Index(fields=['product'], name='wega_relate_product_04621a_idx'),
        ),
        migrations.AddIndex(
            model_name='relatedproduct',
            index=models.Index(fields=['related_product_id'], name='wega_relate_related_a2dffc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='relatedproduct',
            unique_together={('product', 'related_product_id')},
        ),
    ]
