# Generated by Django 5.2.4 on 2026-01-02 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wega', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name'], 'verbose_name': 'Dostawca', 'verbose_name_plural': 'Dostawcy'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ['-start_date'], 'verbose_name': 'Nowość', 'verbose_name_plural': 'Nowości'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkty'},
        ),
        migrations.AlterModelOptions(
            name='productattribute',
            options={'ordering': ['product', 'size', 'color'], 'verbose_name': 'Atrybut produktu', 'verbose_name_plural': 'Atrybuty produktów'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_main', 'order', 'id'], 'verbose_name': 'Obraz produktu', 'verbose_name_plural': 'Obrazy produktów'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'ordering': ['-start_date'], 'verbose_name': 'Promocja', 'verbose_name_plural': 'Promocje'},
        ),
        migrations.AlterModelOptions(
            name='relatedproduct',
            options={'ordering': ['product', 'related_product_id'], 'verbose_name': 'Powiązany produkt', 'verbose_name_plural': 'Powiązane produkty'},
        ),
    ]
