# Generated by Django 5.2.4 on 2026-01-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wega', '0002_alter_category_options_alter_manufacturer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_mapped',
            field=models.BooleanField(default=False, help_text='Czy produkt jest zmapowany do MPD'),
        ),
        migrations.AddField(
            model_name='product',
            name='mapped_product_uid',
            field=models.IntegerField(blank=True, help_text='UID produktu w bazie MPD', null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='is_mapped',
            field=models.BooleanField(blank=True, help_text='Czy wariant jest zmapowany do MPD', null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='mapped_variant_uid',
            field=models.IntegerField(blank=True, help_text='UID wariantu w bazie MPD', null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_mapped'], name='wega_produc_is_mapp_17e973_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['mapped_product_uid'], name='wega_produc_mapped__180c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='productattribute',
            index=models.Index(fields=['is_mapped'], name='wega_produc_is_mapp_26f6cf_idx'),
        ),
        migrations.AddIndex(
            model_name='productattribute',
            index=models.Index(fields=['mapped_variant_uid'], name='wega_produc_mapped__7b8fcc_idx'),
        ),
    ]
