# Generated by Django 5.2.4 on 2025-10-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockhistory',
            name='change_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
