# Generated by Django 5.1.7 on 2025-04-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
                'db_table': 'sources',
                'managed': False,
            },
        ),
    ]
