# Generated by Django 5.2 on 2025-05-08 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0002_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('hex_code', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'db_table': 'colors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductColors',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Product Color',
                'verbose_name_plural': 'Product Colors',
                'db_table': 'product_colors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('variant_id', models.IntegerField(blank=True, null=True)),
                ('file_path', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'db_table': 'product_images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariants',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('variant_id', models.IntegerField()),
                ('total_stock', models.IntegerField(default=0)),
                ('ean', models.CharField(blank=True, max_length=50, null=True)),
                ('variant_uid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'db_table': 'product_variants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mapped_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sets', to='MPD.products')),
            ],
            options={
                'verbose_name': 'Product Set',
                'verbose_name_plural': 'Product Sets',
                'db_table': 'product_set',
            },
        ),
        migrations.CreateModel(
            name='ProductSetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mapped_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_items', to='MPD.products')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='MPD.productset')),
            ],
            options={
                'verbose_name': 'Product Set Item',
                'verbose_name_plural': 'Product Set Items',
                'db_table': 'product_set_items',
            },
        ),
    ]
