# Generated by Django 5.2.4 on 2025-09-05 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0002_alter_productimage_product_alter_products_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productseries',
            options={'managed': True, 'ordering': ['name'], 'verbose_name': 'Seria', 'verbose_name_plural': 'Serie'},
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MPD.attributes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='MPD.products')),
            ],
            options={
                'verbose_name': 'Atrybut produktu',
                'verbose_name_plural': 'Atrybuty produktów',
                'db_table': 'product_attributes',
                'managed': True,
                'unique_together': {('product', 'attribute')},
            },
        ),
    ]
