# Generated by Django 5.2.4 on 2025-09-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0003_alter_productseries_options_productattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='exported_in_full',
            field=models.BooleanField(default=False, verbose_name='Wyeksportowany w full.xml'),
        ),
        migrations.AddField(
            model_name='products',
            name='exported_to_iai',
            field=models.BooleanField(default=False, verbose_name='Wyeksportowany do IAI'),
        ),
    ]
