# Generated by Django 5.2 on 2025-05-17 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0003_colors_productcolors_productimage_productvariants_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productset',
            options={'managed': False, 'verbose_name': 'Product Set', 'verbose_name_plural': 'Product Sets'},
        ),
        migrations.AlterModelOptions(
            name='productsetitem',
            options={'managed': False, 'verbose_name': 'Product Set Item', 'verbose_name_plural': 'Product Set Items'},
        ),
    ]
