# Generated by Django 5.2 on 2025-05-19 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0004_alter_productset_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductColors',
        ),
    ]
