# Generated by Django 5.2.4 on 2025-09-05 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0004_products_exported_in_full_products_exported_to_iai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='exported_in_full',
        ),
    ]
