# Generated by Django 5.2 on 2025-05-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0005_delete_productcolors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSeries',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Seria',
                'verbose_name_plural': 'Serie',
                'db_table': 'product_series',
                'managed': False,
            },
        ),
    ]
