# Generated by Django 5.2.4 on 2025-09-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0006_fix_exported_to_iai_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='exported_to_iai',
            field=models.BooleanField(default=False, verbose_name='Wyeksportowany do IAI'),
        ),
    ]
