# Generated by Django 5.2 on 2025-05-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0006_productseries'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAndPrices',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('variant_id', models.BigIntegerField()),
                ('source_id', models.BigIntegerField()),
                ('stock', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('last_updated', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Stan magazynowy',
                'verbose_name_plural': 'Stany magazynowe',
                'db_table': 'stock_and_prices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('stock_id', models.BigIntegerField()),
                ('source_id', models.BigIntegerField(blank=True, null=True)),
                ('previous_stock', models.IntegerField()),
                ('new_stock', models.IntegerField()),
                ('change_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Historia stanu magazynowego',
                'verbose_name_plural': 'Historia stanów magazynowych',
                'db_table': '',
                'managed': False,
            },
        ),
    ]
