# Generated by Django 5.2 on 2025-05-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0007_stockandprices_stockhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colors',
            options={'managed': True, 'verbose_name': 'Color', 'verbose_name_plural': 'Colors'},
        ),
    ]
