# Generated by Django 5.2 on 2025-05-21 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0008_alter_colors_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='colors',
            name='parent_id',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='MPD.colors'),
        ),
    ]
