# Generated by Django 5.2.4 on 2025-09-06 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0005_remove_products_exported_in_full'),
    ]

    operations = [
    ]
