# Generated by Django 5.2.4 on 2025-09-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0009_fix_exported_to_iai_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariants',
            name='exported_to_iai',
            field=models.BooleanField(default=False, verbose_name='Wyeksportowany do IAI'),
        ),
    ]
