# Generated by Django 5.2 on 2025-05-25 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0009_colors_parent_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stockhistory',
            table='stock_history',
        ),
    ]
