# Generated by Django 5.2.4 on 2025-09-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0010_add_exported_to_iai_to_product_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='exported_to_iai',
        ),
    ]
