# Generated by Django 5.2.4 on 2025-09-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0011_remove_exported_to_iai_from_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariants',
            name='variant_id',
            field=models.AutoField(db_column='variant_id', primary_key=True, serialize=False),
        ),
    ]
