# Generated by Django 5.2 on 2025-06-14 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0011_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sources',
            options={'managed': True, 'verbose_name': 'Source', 'verbose_name_plural': 'Sources'},
        ),
    ]
