# Generated by Django 5.2 on 2025-07-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0013_sources_city_sources_country_sources_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantsRetailPrice',
            fields=[
                ('variant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'product_variants_retail_price',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductvariantsSources',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('variant_id', models.IntegerField()),
                ('ean', models.CharField(blank=True, max_length=50, null=True)),
                ('variant_uid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Product Variant Source',
                'verbose_name_plural': 'Product Variant Sources',
                'db_table': 'product_variants_sources',
                'managed': False,
            },
        ),
    ]
