# Generated by Django 5.2 on 2025-07-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0014_productvariantsretailprice_productvariantssources'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paths',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ścieżka',
                'verbose_name_plural': 'Ścieżki',
                'db_table': 'path',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductPaths',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('path_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Ścieżka produktu',
                'db_table': 'product_path',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vat_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'vat',
                'managed': False,
            },
        ),
    ]
