# Generated by Django 5.2 on 2025-07-15 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0015_paths_productpaths_vat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit_id', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Jednostka',
                'verbose_name_plural': 'Jednostki',
                'db_table': 'units',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FabricComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'fabric_component',
            },
        ),
        migrations.CreateModel(
            name='ProductFabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveSmallIntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MPD.fabriccomponent')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabrics', to='MPD.products')),
            ],
            options={
                'db_table': 'product_fabric',
                'unique_together': {('product', 'component')},
            },
        ),
    ]
