# Generated by Django 5.2.4 on 2025-08-08 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0016_units_fabriccomponent_productfabric'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportTracking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('export_type', models.CharField(max_length=255)),
                ('last_exported_product_id', models.BigIntegerField()),
                ('last_exported_timestamp', models.DateTimeField()),
                ('total_products_exported', models.BigIntegerField()),
                ('export_status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Status eksportu',
                'verbose_name_plural': 'Statusy eksportu',
                'db_table': 'xml_export_tracking',
                'managed': False,
            },
        ),
    ]
