# Generated by Django 5.2.4 on 2025-08-18 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0018_attributes'),
    ]

    operations = [
        migrations.RunSQL(
            # Forward SQL - utwórz tabelę
            """
            CREATE TABLE IF NOT EXISTS iai_product_counter (
                id INTEGER PRIMARY KEY DEFAULT 1,
                counter_value BIGINT NOT NULL DEFAULT 0,
                CONSTRAINT single_row CHECK (id = 1)
            );
            
            -- Inicjalizuj tabelę z wartością początkową
            INSERT INTO iai_product_counter (id, counter_value) 
            VALUES (1, 0) 
            ON CONFLICT (id) DO NOTHING;
            
            -- Ustaw aktualną wartość licznika na maksymalną wartość iai_product_id + 1
            -- (jeśli tabela product_variants już istnieje i ma dane)
            UPDATE iai_product_counter 
            SET counter_value = COALESCE((SELECT MAX(iai_product_id) FROM product_variants), 0) + 1
            WHERE id = 1;
            """,

            # Reverse SQL - usuń tabelę
            """
            DROP TABLE IF EXISTS iai_product_counter;
            """
        ),
    ]
