# Generated by Django 5.2.4 on 2025-08-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0019_iai_product_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='IaiProductCounter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('counter_value', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Licznik IAI Product ID',
                'verbose_name_plural': 'Liczniki IAI Product ID',
                'db_table': 'iai_product_counter',
                'managed': False,
            },
        ),
    ]
