# Generated by Django 5.2.4 on 2025-08-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0020_iaiproductcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullChangeFile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('timestamp', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('bucket_url', models.URLField(blank=True, null=True)),
                ('local_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('created_at_record', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Plik Full Change',
                'verbose_name_plural': 'Pliki Full Change',
                'db_table': 'full_change_files',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
