# Generated by Django 5.2.4 on 2025-08-27 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0021_fullchangefile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExportTracking',
        ),
    ]
