# Generated by Django 5.2.4 on 2025-08-29 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0022_delete_exporttracking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fullchangefile',
            options={'managed': False, 'ordering': ['-created_at'], 'verbose_name': 'Plik XML', 'verbose_name_plural': 'Pliki XML'},
        ),
    ]
