# Generated by Django 5.2.4 on 2025-08-31 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0023_alter_fullchangefile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='colors',
            name='iai_colors_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
