# Generated by Django 5.2.4 on 2025-08-31 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MPD', '0024_colors_iai_colors_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributes',
            options={'managed': True, 'verbose_name': 'Attribute', 'verbose_name_plural': 'Attributes'},
        ),
        migrations.AlterModelOptions(
            name='brands',
            options={'managed': True, 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'managed': True, 'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='fullchangefile',
            options={'managed': True, 'ordering': ['-created_at'], 'verbose_name': 'Plik XML', 'verbose_name_plural': 'Pliki XML'},
        ),
        migrations.AlterModelOptions(
            name='iaiproductcounter',
            options={'managed': True, 'verbose_name': 'Licznik IAI Product ID', 'verbose_name_plural': 'Liczniki IAI Product ID'},
        ),
        migrations.AlterModelOptions(
            name='paths',
            options={'managed': True, 'verbose_name': 'Ścieżka', 'verbose_name_plural': 'Ścieżki'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'managed': True, 'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='productpaths',
            options={'managed': True, 'verbose_name': 'Ścieżka produktu', 'verbose_name_plural': 'Ścieżki produktów'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'managed': True, 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productseries',
            options={'managed': True, 'verbose_name': 'Seria', 'verbose_name_plural': 'Serie'},
        ),
        migrations.AlterModelOptions(
            name='productset',
            options={'managed': True, 'verbose_name': 'Product Set', 'verbose_name_plural': 'Product Sets'},
        ),
        migrations.AlterModelOptions(
            name='productsetitem',
            options={'managed': True, 'verbose_name': 'Product Set Item', 'verbose_name_plural': 'Product Set Items'},
        ),
        migrations.AlterModelOptions(
            name='productvariants',
            options={'managed': True, 'verbose_name': 'Product Variant', 'verbose_name_plural': 'Product Variants'},
        ),
        migrations.AlterModelOptions(
            name='productvariantsretailprice',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productvariantssources',
            options={'managed': True, 'verbose_name': 'Product Variant Source', 'verbose_name_plural': 'Product Variant Sources'},
        ),
        migrations.AlterModelOptions(
            name='sizes',
            options={'managed': True, 'verbose_name': 'Size', 'verbose_name_plural': 'Sizes'},
        ),
        migrations.AlterModelOptions(
            name='stockandprices',
            options={'managed': True, 'verbose_name': 'Stan magazynowy', 'verbose_name_plural': 'Stany magazynowe'},
        ),
        migrations.AlterModelOptions(
            name='stockhistory',
            options={'managed': True, 'verbose_name': 'Historia stanu magazynowego', 'verbose_name_plural': 'Historia stanów magazynowych'},
        ),
        migrations.AlterModelOptions(
            name='units',
            options={'managed': True, 'verbose_name': 'Jednostka', 'verbose_name_plural': 'Jednostki'},
        ),
        migrations.AlterModelOptions(
            name='vat',
            options={'managed': True},
        ),
    ]
