# Generated by Django 5.2.4 on 2025-08-15 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa zadania')),
                ('url', models.URLField(verbose_name='URL do scrapowania')),
                ('status', models.CharField(choices=[('pending', 'Oczekujące'), ('running', 'W trakcie'), ('completed', 'Zakończone'), ('failed', 'Błąd'), ('cancelled', 'Anulowane')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Data rozpoczęcia')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data zakończenia')),
                ('error_message', models.TextField(blank=True, verbose_name='Komunikat błędu')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Liczba prób')),
                ('max_retries', models.IntegerField(default=3, verbose_name='Maksymalna liczba prób')),
                ('selectors', models.JSONField(blank=True, default=dict, verbose_name='Selektory CSS')),
                ('wait_time', models.IntegerField(default=5, verbose_name='Czas oczekiwania (sekundy)')),
                ('use_selenium', models.BooleanField(default=False, verbose_name='Użyj Selenium')),
                ('headless', models.BooleanField(default=True, verbose_name='Tryb headless')),
            ],
            options={
                'verbose_name': 'Zadanie Scraping',
                'verbose_name_plural': 'Zadania Scraping',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa sesji')),
                ('url', models.URLField(verbose_name='URL docelowy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='Nagłówki HTTP')),
                ('cookies', models.JSONField(blank=True, default=dict, verbose_name='Cookies')),
                ('proxy', models.CharField(blank=True, max_length=255, verbose_name='Proxy')),
                ('timeout', models.IntegerField(default=30, verbose_name='Timeout (sekundy)')),
            ],
            options={
                'verbose_name': 'Sesja Web',
                'verbose_name_plural': 'Sesje Web',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, verbose_name='Dane')),
                ('raw_html', models.TextField(blank=True, verbose_name='Surowy HTML')),
                ('screenshot_path', models.CharField(blank=True, max_length=500, verbose_name='Ścieżka do screenshot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_agent.scrapingtask', verbose_name='Zadanie')),
            ],
            options={
                'verbose_name': 'Wynik Scraping',
                'verbose_name_plural': 'Wyniki Scraping',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebAgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], max_length=10, verbose_name='Poziom')),
                ('message', models.TextField(verbose_name='Wiadomość')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_agent.scrapingtask', verbose_name='Zadanie')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_agent.websession', verbose_name='Sesja')),
            ],
            options={
                'verbose_name': 'Log Web Agent',
                'verbose_name_plural': 'Logi Web Agent',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='scrapingtask',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_agent.websession', verbose_name='Sesja'),
        ),
    ]
