# Generated by Django 5.2.4 on 2025-10-06 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebAgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('config_data', models.JSONField(verbose_name='Dane konfiguracji')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
            ],
            options={
                'verbose_name': 'Konfiguracja agenta web',
                'verbose_name_plural': 'Konfiguracje agenta web',
                'db_table': 'web_agent_configs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebAgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa zadania')),
                ('task_type', models.CharField(choices=[('scrape', 'Scraping'), ('monitor', 'Monitorowanie'), ('data_collection', 'Zbieranie danych'), ('automation', 'Automatyzacja')], max_length=50, verbose_name='Typ zadania')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('status', models.CharField(choices=[('pending', 'Oczekujące'), ('running', 'W trakcie'), ('completed', 'Zakończone'), ('failed', 'Niepowodzenie'), ('cancelled', 'Anulowane')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Data rozpoczęcia')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data zakończenia')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='Konfiguracja')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='Wynik')),
                ('error_message', models.TextField(blank=True, verbose_name='Komunikat błędu')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, verbose_name='ID zadania Celery')),
            ],
            options={
                'verbose_name': 'Zadanie agenta web',
                'verbose_name_plural': 'Zadania agenta web',
                'db_table': 'web_agent_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebAgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Informacja'), ('WARNING', 'Ostrzeżenie'), ('ERROR', 'Błąd'), ('CRITICAL', 'Krytyczny')], max_length=10, verbose_name='Poziom logu')),
                ('message', models.TextField(verbose_name='Wiadomość')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Znacznik czasu')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Dodatkowe dane')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='web_agent.webagenttask', verbose_name='Zadanie')),
            ],
            options={
                'verbose_name': 'Log agenta web',
                'verbose_name_plural': 'Logi agenta web',
                'db_table': 'web_agent_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
