# Generated by Django 5.2.4 on 2025-11-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webagenttask',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name': 'Zadanie agenta web', 'verbose_name_plural': 'Zadania agenta web'},
        ),
        migrations.AddField(
            model_name='webagenttask',
            name='brand_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='ID marki'),
        ),
        migrations.AddField(
            model_name='webagenttask',
            name='brand_name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Nazwa marki'),
        ),
        migrations.AddField(
            model_name='webagenttask',
            name='priority',
            field=models.IntegerField(default=0, help_text='Wyższa wartość = wyższy priorytet', verbose_name='Priorytet'),
        ),
        migrations.AddIndex(
            model_name='webagenttask',
            index=models.Index(fields=['brand_id', 'status'], name='web_agent_t_brand_i_f96ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='webagenttask',
            index=models.Index(fields=['brand_name', 'status'], name='web_agent_t_brand_n_9b1d1b_idx'),
        ),
    ]
