# Generated by Django 5.2.4 on 2025-12-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('brand_id', models.IntegerField(db_index=True, unique=True, verbose_name='ID marki')),
                ('brand_name', models.CharField(max_length=200, verbose_name='Nazwa marki')),
                ('default_active_filter', models.BooleanField(blank=True, null=True, verbose_name='Domyślny filtr active')),
                ('default_is_mapped_filter', models.BooleanField(blank=True, null=True, verbose_name='Domyślny filtr is_mapped')),
                ('color_mapping', models.JSONField(blank=True, default=dict, help_text='JSON: {"Dark Brown": "Ciemny Brąz", "Beige": "Beż", ...}', verbose_name='Mapowanie kolorów producenta')),
                ('attributes', models.JSONField(blank=True, default=list, help_text='Lista atrybutów do wyszukiwania w opisie produktu: ["Bawełna", "Elastan", "Bambus", ...]', verbose_name='Lista atrybutów do wyszukiwania')),
                ('similarity_threshold', models.FloatField(default=0.7, help_text='Próg podobieństwa dla wyszukiwania atrybutów (0.0-1.0, domyślnie 0.7)', verbose_name='Próg podobieństwa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
            ],
            options={
                'verbose_name': 'Konfiguracja marki',
                'verbose_name_plural': 'Konfiguracje marek',
                'db_table': 'brand_config',
                'ordering': ['brand_name'],
                'indexes': [models.Index(fields=['brand_id'], name='brand_confi_brand_i_f80de2_idx'), models.Index(fields=['brand_name'], name='brand_confi_brand_n_553e34_idx')],
            },
        ),
    ]
