# Generated by Django 5.2.4 on 2025-12-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_agent', '0003_producercolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrun',
            name='logs',
            field=models.TextField(blank=True, help_text='Logi automatyzacji w czasie rzeczywistym', null=True, verbose_name='Logi'),
        ),
    ]
