name: Deploy Django App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: pawlo884
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ env.DOCKERHUB_USERNAME }}/django-app:latest
        
    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.DROPLET_SSH_KEY }}
        
    - name: Deploy to DigitalOcean
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.DROPLET_HOST }} >> ~/.ssh/known_hosts
        ssh ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_HOST }} '
          echo "Testing connection..."
          whoami
          pwd
          ls -la ~/.ssh/
          echo "Deploying application..."
          cd /app
          docker-compose pull
          docker-compose up -d
        ' 